=== 007au/pfsense-packages/packages/schema/packages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/* $Id$ */
/* ========================================================================== */
/*
    package.dtd
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
-->
<!ELEMENT version (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT tooltiptext (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT savetext (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT tabs ((tab*))>
<!ELEMENT tab ((text, url, active?))>
<!ELEMENT service ((name, rcfile, executable?))>
<!ELEMENT section (#PCDATA)>
<!ELEMENT requirements (#PCDATA)>
<!ELEMENT rcfile (#PCDATA)>
<!ELEMENT executable (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT packagegui ((copyright, description, requirements, faq, name, version, title, note?, savetext?, aftersaveredirect?, include_file?, menu*, service?, tabs?, configpath?, adddeleteeditpagefields?, additional_files_needed*, fields?, custom_php_global_functions?, custom_php_command_before_form?, custom_delete_php_command?, custom_add_php_command?, custom_php_resync_config_command?, custom_php_validation_command?, custom_add_php_command_late?, start_command?, restart_command?, custom_php_after_form_command?, custom_php_resync_config_command?, custom_php_install_command?, custom_php_deinstall_command?))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT menu ((name, tooltiptext?, section?, configfile?, url?))>
<!ELEMENT item (#PCDATA)>
<!ELEMENT include_file (#PCDATA)>
<!ELEMENT aftersaveredirect (#PCDATA)>
<!ELEMENT faq (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT donotdisable (#PCDATA)>
<!ELEMENT enablefields (#PCDATA)>
<!ELEMENT required EMPTY>
<!ELEMENT multiple (#PCDATA)>
<!ELEMENT default_value (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT options ((option+))>
<!ELEMENT option ((name, value))>
<!ELEMENT fields ((field+))>
<!ELEMENT fieldname (#PCDATA)>
<!ELEMENT fielddescr (#PCDATA)>
<!ELEMENT field ((fielddescr, fieldname, description?, type, donotdisable?, enablefields?, size?, required?, default_value?, value?, multiple?, options?))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT custom_php_global_functions (#PCDATA)>
<!ELEMENT custom_php_command_before_form (#PCDATA)>
<!ELEMENT custom_delete_php_command (#PCDATA)>
<!ELEMENT custom_add_php_command (#PCDATA)>
<!ELEMENT custom_php_resync_config_command (#PCDATA)>
<!ELEMENT custom_php_validation_command (#PCDATA)>
<!ELEMENT custom_add_php_command_late (#PCDATA)>
<!ELEMENT start_command (#PCDATA)>
<!ELEMENT restart_command (#PCDATA)>
<!ELEMENT custom_php_after_form_command (#PCDATA)>
<!ELEMENT custom_php_install_command (#PCDATA)>
<!ELEMENT custom_php_deinstall_command (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT configpath (#PCDATA)>
<!ELEMENT configfile (#PCDATA)>
<!ELEMENT chmod (#PCDATA)>
<!ELEMENT columnitem ((fielddescr, fieldname))>
<!ELEMENT adddeleteeditpagefields ((columnitem+))>
<!ELEMENT additional_files_needed ((prefix, chmod, item))>
<!ELEMENT active EMPTY>

=== 007au/pfsense-packages/packages/squidGuard/squidguard_src.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
	<description>Describe your package here</description>
	<requirements>Describe your package requirements here</requirements>
	<faq>Currently there are no FAQ items provided.</faq>

	<name>squidguardsrc</name>
	<version>none</version>
	<title>Proxy server filter SquidGuard: Sources</title>
	<include_file>squidguard.inc</include_file>

	<delete_string>A proxy server user has been deleted.</delete_string>
	<addedit_string>A proxy server user has been created/modified.</addedit_string>

	<tabs>
		<tab>
			<text>General settings</text>
			<url>/pkg_edit.php?xml=squidguard.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Default</text>
			<url>/pkg_edit.php?xml=squidguard_default.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>ACL</text>
			<url>/pkg.php?xml=squidguard_acl.xml</url>
		</tab>
		<tab>
			<text>Sources</text>
			<url>/pkg.php?xml=squidguard_src.xml</url>
			<active/>
		</tab>
		<tab>
			<text>Destinations</text>
			<url>/pkg.php?xml=squidguard_dest.xml</url>			
		</tab>
		<tab>
			<text>Times</text>
			<url>/pkg.php?xml=squidguard_time.xml</url>
		</tab>
		<tab>
			<text>Rewrites</text>
			<url>/pkg.php?xml=squidguard_rewr.xml</url>
		</tab>
		<tab>
			<text>Log</text>
			<url>/pkg_edit.php?xml=squidguard_log.xml</url>
		</tab>
	</tabs>
	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Source name</fielddescr>
			<fieldname>name</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>IP list</fielddescr>
			<fieldname>iplist</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
		</columnitem>
	</adddeleteeditpagefields>
	<fields>
		<field>
			<fielddescr>Source name</fielddescr>
			<fieldname>name</fieldname>
			<description>
				You can enter name here. Name consist minimum 2 symbols, first from which letter. &lt;br&gt;
				All other symbols is [a-Z_0-9]. Source name must be &lt;b&gt;unique&lt;/b&gt; .
			</description>
			<type>input</type>
			<size>80</size>
			<required/>
		</field>
		<field>
			<fielddescr>IP addresses</fielddescr>
			<fieldname>iplist</fieldname>
			<description>
				Enter IP addresses here with space(' ') divider. &lt;br&gt; 
				IP addresses must be in format:&lt;br&gt; 
				ip xxx.xxx.xxx.xxx [...] or ip xxx.xxx.xxx.xxx/nn [...] or &lt;br&gt; 
				ip xxx.xxx.xxx.xxx/mmm.mmm.mmm.mmm [...] or ip xxx.xxx.xxx.xxx-yyy.yyy.yyy.yyy [...] &lt;br&gt; 
				where: &lt;br&gt; 
				xxx.xxx.xxx.xxx is an IP address (host or net, i.e. 10.11.12.13 or 10.11.12.0), /nn a net prefix (i.e. /23), &lt;br&gt; 
				mmm.mmm.mmm.mmm is a netmask (i.e. 255.255.254.0) and	yyy.yyy.yyy.yyy is a host address &lt;br&gt; 
				(must be >= xxx.xxx.xxx.xxx)	
			</description>
			<type>textarea</type>
			<cols>50</cols>
			<rows>10</rows>
		</field>
		<field>
			<fielddescr>Enable log</fielddescr>
			<fieldname>enablelog</fieldname>
			<description>Check this for enable log.</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
			<description></description>
			<type>input</type>
			<size>80</size>
		</field>
	</fields>
	<custom_php_after_form_command> 
               squidGuard_print_javascript();
	</custom_php_after_form_command>
	<custom_php_validation_command>
		squidguard_validate_source($_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_php_resync_config_command>
//		squidguard_resync_time();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/packages/squidGuard/squidguard_rewr.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>

	<name>squidguardrewrite</name>
	<version>none</version>
	<title>Proxy Content filter SquidGuard: Rewrites</title>
	<include_file>/usr/local/pkg/squidguard.inc</include_file>

	<tabs>
		<tab>
			<text>General settings</text>
			<url>/pkg_edit.php?xml=squidguard.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Default</text>
			<url>/pkg_edit.php?xml=squidguard_default.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>ACL</text>
			<url>/pkg.php?xml=squidguard_acl.xml</url>
		</tab>
		<tab>
			<text>Destinations</text>
			<url>/pkg.php?xml=squidguard_dest.xml</url>			
		</tab>
		<tab>
			<text>Times</text>
			<url>/pkg.php?xml=squidguard_time.xml</url>
		</tab>
		<tab>
			<text>Rewrites</text>
			<url>/pkg.php?xml=squidguard_rewr.xml</url>
			<active/>
		</tab>
		<tab>
			<text>Log</text>
			<url>/pkg_edit.php?xml=squidguard_log.xml</url>
		</tab>
	</tabs>
	
	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Name</fielddescr>
			<fieldname>name</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
		</columnitem>
	</adddeleteeditpagefields>

	<fields>		
		<field>
			<fielddescr>Name</fielddescr>
			<fieldname>name</fieldname>
			<description>
				You may enter name here. Name must consist of minimum 2 symbols, first from which letter. &lt;br&gt;
				All other symbols must be [a-Z_0-9].				
			</description>
			<type>input</type>
			<required/>
			<size>100</size>
		</field>
		<field>
			<fielddescr>
				&lt;b&gt;Rewrite rule.&lt;/b&gt;&lt;br&gt;
				Define how url will be replaced.</fielddescr>
			<type>rowhelper</type>
			<rowhelper>
				<rowhelperfield>
					<fielddescr>Target URL or regular expression</fielddescr>
					<fieldname>targeturl</fieldname>
					<type>input</type>
					<size>50</size>
				</rowhelperfield>
				<rowhelperfield>
					<fielddescr>Replace to URL</fielddescr>
					<fieldname>replaceto</fieldname>
					<type>input</type>
					<size>69</size>
				</rowhelperfield>
				
<!--				<rowhelperfield>
					<fielddescr>Case ins.</fielddescr>
					<fieldname>caseins</fieldname>
					<type>checkbox</type>
				</rowhelperfield>
				<rowhelperfield>
					<fielddescr>Http 301</fielddescr>
					<fieldname>http301</fieldname>
					<type>checkbox</type>
				</rowhelperfield>
				<rowhelperfield>
					<fielddescr>Http 302</fielddescr>
					<fieldname>http302</fieldname>
					<type>checkbox</type>
				</rowhelperfield>
-->
			</rowhelper>
		</field>
		<field>
			<fielddescr>Enable log</fielddescr>
			<fieldname>enablelog</fieldname>
			<description>Check this for enable log.</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
			<description>You may enter a description here for your reference (not parsed).&lt;br&gt;
				&lt;b&gt; Note: &lt;/b&gt; &lt;br&gt;
				&lt;b&gt;Rewrite rule&lt;/b&gt; - define how url will are replaced.&lt;br&gt;
				&lt;b&gt;Target URL or regular expression&lt;/b&gt; - contains destination url or regular expression. Regular expression example: */cc32e46.exe &lt;br&gt;
				&lt;b&gt;Replace to&lt;/b&gt; - contains replacing url.		
			</description>
			<type>input</type>
			<size>100</size>
		</field>
	</fields>

	<custom_php_after_form_command> 
		squidGuard_print_javascript();
	</custom_php_after_form_command>
	<custom_php_validation_command>
		squidguard_validate_rewrite($_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_php_resync_config_command>
//		squidguard_resync_rewrite();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/packages/p3scan-pf/p3scan-pf-spam.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
  <description>Describe your package here</description>
  <requirements>Describe your package requirements here</requirements>
  <faq>Currently there are no FAQ items provided.</faq>
    <!-- change this if configpath works -->
  <name>p3scanpfspam</name>
  <version>1.0</version>
  <title>Services: POP3 Proxy: SPAM Settings</title>
  <note>
    This &lt;acronym title=&quot;Hypertext Markup Language&quot;&gt;HTML&lt;/acronym&gt; page uses default values, hence even if each field is 
    set, you are still required to save this page if you are editing this page
    for the very first time!
  </note>
  <aftersaveredirect>pkg_edit.php?xml=p3scan-pf-spam.xml&amp;id=0</aftersaveredirect>
  <include_file>p3scan-pf.inc</include_file>
  <tabs>
    <tab>
      <text>Daemon Settings</text>
      <url>/pkg_edit.php?xml=p3scan-pf.xml&amp;id=0</url>
    </tab>
    <tab>
      <text>Transparent Proxy Exclusion</text>
      <url>/pkg.php?xml=p3scan-pf-transex.xml</url>
    </tab>
    <tab>
      <text>Message Processing</text>
      <url>pkg_edit.php?xml=p3scan-pf-msg.xml&amp;id=0</url>
    </tab>
    <tab>
      <text>Emergency Contact</text>
      <url>/pkg.php?xml=p3scan-pf-emer.xml</url>
    </tab>
    <tab>
      <text>Virus Scanner Settings</text>
      <url>/pkg_edit.php?xml=p3scan-pf-vir.xml&amp;id=0</url>
    </tab>
    <tab>
      <text>SPAM Settings</text>
      <url>/pkg_edit.php?xml=p3scan-pf-spam.xml&amp;id=0</url>
      <active />
    </tab>
  </tabs>
  <!-- 
    configpath gets expanded out automatically and config items
    will be stored in that location
  -->
  <configpath>['installedpackages']['p3scanpf']['config']['spam']</configpath>
  <!--
    fields gets invoked when the user adds or edits a item. The following items
    will be parsed and rendered for the user as a gui with input, and selectboxes.
  -->
  <fields>
    <field>
      <fielddescr>Enable Spam Checking</fielddescr>
      <fieldname>checkspam</fieldname>
      <description>
        If set, will scan for Spam before scanning for a virus.
      </description>
      <type>checkbox</type>
      <donotdisable>true</donotdisable>
      <enablefields>spamcheck</enablefields>
    </field>
    <field>
      <fielddescr>SPAM Executable Command</fielddescr>
      <fieldname>spamcheck</fieldname>
      <description>The command (plus arguments) that should be invoked to check for SPAM messages.</description>
      <type>input</type>
      <size>70</size>
      <!-- the below tag plus its inline text must be on one single line. -->
      <default_value>/usr/local/bin/dspam --user dspamuser --mode=teft --stdout --deliver=innocent,spam --feature=ch,no,wh</default_value>
    </field>
  </fields>
  <!--
    Arbitrary PHP Code, that gets executed if a certain event gets triggered.
  -->
  <custom_php_resync_config_command>
    sync_package_p3scan();
  </custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/packages/squidGuard/squidguard.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>

	<name>squidguardgeneral</name>
	<version>1.2.0_1</version>
	<title>Proxy Content filter SquidGuard: General settings</title>
	<include_file>/usr/local/pkg/squidguard.inc</include_file>

	<!-- Installation -->
	<menu>
		<name>Proxy Content filter</name>
		<tooltiptext>Modify the proxy server's filter settings</tooltiptext>
		<section>Services</section>
		<url>/pkg_edit.php?xml=squidguard.xml&amp;id=0</url>
	</menu>

	<tabs>
		<tab>
			<text>General settings</text>
			<url>/pkg_edit.php?xml=squidguard.xml&amp;id=0</url>
			<active/>
		</tab>
		<tab>
			<text>Default</text>
			<url>/pkg_edit.php?xml=squidguard_default.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>ACL</text>
			<url>/pkg.php?xml=squidguard_acl.xml</url>
		</tab>
		<tab>
			<text>Destinations</text>
			<url>/pkg.php?xml=squidguard_dest.xml</url>			
		</tab>
		<tab>
			<text>Times</text>
			<url>/pkg.php?xml=squidguard_time.xml</url>
		</tab>
		<tab>
			<text>Rewrites</text>
			<url>/pkg.php?xml=squidguard_rewr.xml</url>
		</tab>
		<tab>
			<text>Log</text>
			<url>/pkg_edit.php?xml=squidguard_log.xml</url>
		</tab>
	</tabs>
	
	<service>
		<name>squidGuard</name>
		<description>Proxy server filter Service</description>
		<executable>squidGuard</executable>
	</service>

	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard.inc</item>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_configurator.inc</item>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_acl.xml</item>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_default.xml</item>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_dest.xml</item>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_rewr.xml</item>
	</additional_files_needed>
<!--
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_src.xml</item>
	</additional_files_needed>
-->
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_time.xml</item>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/squidGuard/squidguard_log.xml</item>
	</additional_files_needed>
	<additional_files_needed>
		<prefix>/usr/local/www/</prefix>
		<chmod>0755</chmod>
		<item>http://www.pfsense.org/packages/config/squidGuard/sgerror.php</item>
	</additional_files_needed>

	<fields>		
		<field>
			<fielddescr>Enable</fielddescr>
			<fieldname>squidguard_enable</fieldname>
			<description>Check this for enable squidGuard</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Blacklist</fielddescr>
			<fieldname>blacklist</fieldname>
			<description>Check this for enable blacklist</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Blacklist proxy</fielddescr>
			<fieldname>blacklist_proxy</fieldname>
			<description>
				Blacklist upload proxy - enter here, or leave blank. 
				Format: host:[port login:pass] . Default proxy port 1080. 
				Example: '192.168.0.1:8080 user:pass' 
			</description>
			<type>input</type>
			<size>100</size>
		</field>
		<field>
			<fielddescr>Blacklist URL</fielddescr>
			<fieldname>blacklist_url</fieldname>
			<description>Enter FTP, HTTP or LOCAL (pfSense) URL blacklist archive, or leave blank.</description>
			<type>input</type>
			<size>100</size>
		</field>
		<field>
			<fielddescr>Redirect mode</fielddescr>
			<fieldname>redirect_mode</fieldname>
			<description>
				Select redirect mode here. If you selected 'Internal', then will use internal 'sgerror.php' page. 
				Else - all redirect url's will added 'as it is'. In this situation you can't use 'HTTP error codes',
				'BLANK' and 'BLANK_IMG' extensions, only you self error page URL.				
			</description>
			<type>select</type>
			<value>rmod_int</value>
			<options>
				<option><name>Internal</name><value>rmod_int</value></option>
				<option><name>External as Moved (http '301' code)</name><value>rmod_301</value></option>
				<option><name>External as Found (http '302' code)</name><value>rmod_302</value></option>
			</options>
		</field>
		<field>
			<fielddescr>Emulate error HTTP header</fielddescr>
			<fieldname>emu_err_http_hdr</fieldname>
			<description>
				Check this for enable emulation error code HTTP header, 
				when proxy-filter deny access to URL with specified HTTP error code 
				in 'Redirect' field's. This may change behaviour client's IE brouser 
				and affiliated proxy.
			</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>View GUI log</fielddescr>
			<fieldname>view_gui_log</fieldname>
			<description>Check this for view GUI log</description>
			<type>checkbox</type>
		</field>
	</fields>
	<custom_add_php_command/>
	<custom_php_command_before_form>
		squidguard_before_form(&amp;$pkg);
	</custom_php_command_before_form>
	<custom_php_after_form_command> 
        squidGuard_print_javascript();
	</custom_php_after_form_command>
	<custom_php_resync_config_command>
		squidguard_resync();
	</custom_php_resync_config_command>
	<custom_php_install_command>
		squidguard_install_command();
		squidguard_resync();
	</custom_php_install_command>
	<custom_php_deinstall_command>
		squidguard_deinstall_command();
	</custom_php_deinstall_command>
</packagegui>
