=== 007au/pfsense-packages/packages/schema/packages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/* $Id$ */
/* ========================================================================== */
/*
    package.dtd
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
-->
<!ELEMENT version (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT tooltiptext (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT savetext (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT tabs ((tab*))>
<!ELEMENT tab ((text, url, active?))>
<!ELEMENT service ((name, rcfile, executable?))>
<!ELEMENT section (#PCDATA)>
<!ELEMENT requirements (#PCDATA)>
<!ELEMENT rcfile (#PCDATA)>
<!ELEMENT executable (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT packagegui ((copyright, description, requirements, faq, name, version, title, note?, savetext?, aftersaveredirect?, include_file?, menu*, service?, tabs?, configpath?, adddeleteeditpagefields?, additional_files_needed*, fields?, custom_php_global_functions?, custom_php_command_before_form?, custom_delete_php_command?, custom_add_php_command?, custom_php_resync_config_command?, custom_php_validation_command?, custom_add_php_command_late?, start_command?, restart_command?, custom_php_after_form_command?, custom_php_resync_config_command?, custom_php_install_command?, custom_php_deinstall_command?))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT menu ((name, tooltiptext?, section?, configfile?, url?))>
<!ELEMENT item (#PCDATA)>
<!ELEMENT include_file (#PCDATA)>
<!ELEMENT aftersaveredirect (#PCDATA)>
<!ELEMENT faq (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT donotdisable (#PCDATA)>
<!ELEMENT enablefields (#PCDATA)>
<!ELEMENT required EMPTY>
<!ELEMENT multiple (#PCDATA)>
<!ELEMENT default_value (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT options ((option+))>
<!ELEMENT option ((name, value))>
<!ELEMENT fields ((field+))>
<!ELEMENT fieldname (#PCDATA)>
<!ELEMENT fielddescr (#PCDATA)>
<!ELEMENT field ((fielddescr, fieldname, description?, type, donotdisable?, enablefields?, size?, required?, default_value?, value?, multiple?, options?))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT custom_php_global_functions (#PCDATA)>
<!ELEMENT custom_php_command_before_form (#PCDATA)>
<!ELEMENT custom_delete_php_command (#PCDATA)>
<!ELEMENT custom_add_php_command (#PCDATA)>
<!ELEMENT custom_php_resync_config_command (#PCDATA)>
<!ELEMENT custom_php_validation_command (#PCDATA)>
<!ELEMENT custom_add_php_command_late (#PCDATA)>
<!ELEMENT start_command (#PCDATA)>
<!ELEMENT restart_command (#PCDATA)>
<!ELEMENT custom_php_after_form_command (#PCDATA)>
<!ELEMENT custom_php_install_command (#PCDATA)>
<!ELEMENT custom_php_deinstall_command (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT configpath (#PCDATA)>
<!ELEMENT configfile (#PCDATA)>
<!ELEMENT chmod (#PCDATA)>
<!ELEMENT columnitem ((fielddescr, fieldname))>
<!ELEMENT adddeleteeditpagefields ((columnitem+))>
<!ELEMENT additional_files_needed ((prefix, chmod, item))>
<!ELEMENT active EMPTY>

=== 007au/pfsense-packages/packages/freeswitch/freeswitch_gateways.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*

    freeswitch_gateways.xml
    Copyright (C) 2008 Mark J Crane
    All rights reserved.
    
    FreeSWITCH (TM)
    http://www.freeswitch.org/
    
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 to whom it may belong
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
         </copyright>
    <description>FreeSWITCH is an open source telephony platform designed to facilitate the creation of voice and chat driven products scaling from a soft-phone up to a soft-switch.  It can be used as a simple switching engine, a PBX, a media gateway or a media server to host IVR applications using simple scripts or XML to control the callflow.</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>freeswitchgateways</name>
	<version>0.2</version>
	<title>FreeSWITCH: Gateways</title>
	<include_file>/usr/local/pkg/freeswitch.inc</include_file>
	<tabs>
		<tab>
			<text>Settings</text>
			<url>/pkg_edit.php?xml=freeswitch.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Dialplan</text>
			<url>/pkg_edit.php?xml=freeswitch_dialplan.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Extensions</text>
			<url>/pkg.php?xml=freeswitch_extensions.xml</url>
		</tab>
		<tab>
			<text>External</text>
			<url>/pkg_edit.php?xml=freeswitch_external.xml&amp;id=0</url>
		</tab>		
		<tab>
			<text>Gateways</text>
			<url>/pkg.php?xml=freeswitch_gateways.xml</url>
			<active/>
		</tab>
		<tab>
			<text>Internal</text>
			<url>/pkg_edit.php?xml=freeswitch_internal.xml&amp;id=0</url>
		</tab>		
		<tab>
			<text>Modules</text>
			<url>/pkg_edit.php?xml=freeswitch_modules.xml&amp;id=0</url>
		</tab>		
		<tab>
			<text>Public</text>
			<url>/pkg_edit.php?xml=freeswitch_public.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Status</text>
			<url>/freeswitch/freeswitch_status.php</url>
		</tab>    		
		<tab>
			<text>Vars</text>
			<url>/pkg_edit.php?xml=freeswitch_vars.xml&amp;id=0</url>
		</tab>
	</tabs>
	<configpath>installedpackages->package->$packagename->configuration->gateways</configpath>
	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Gateway</fielddescr>
			<fieldname>gateway</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Context</fielddescr>
			<fieldname>context</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
		</columnitem>
	</adddeleteeditpagefields>
	<fields>
		<field>
			<fielddescr>Gateway</fielddescr>
			<fieldname>gateway</fieldname>
			<description>Enter the gateway name here.</description>
			<type>input</type>
			<value></value>			
		</field>
		<field>
			<fielddescr>Username</fielddescr>
			<fieldname>username</fieldname>
			<description>Enter the username here.</description>
			<type>input</type>
			<value></value>			
		</field>
		<field>
			<fielddescr>Password</fielddescr>
			<fieldname>password</fieldname>
			<description>Enter the password here.</description>
			<type>input</type>
			<value></value>			
		</field>
		<field>
			<fielddescr>Realm</fielddescr>
			<fieldname>realm</fieldname>
			<description>Enter the realm here.</description>
			<type>input</type>
			<value></value>			
		</field>				
		<field>
			<fielddescr>From-user</fielddescr>
			<fieldname>from-user</fieldname>
			<description>Enter the from-user here.</description>
			<type>input</type>
			<value></value>			
		</field>
		<field>
			<fielddescr>From-domain</fielddescr>
			<fieldname>from-domain</fieldname>
			<description>Enter the from-domain here.</description>
			<type>input</type>
			<value></value>			
		</field>
		<field>
			<fielddescr>Proxy</fielddescr>
			<fieldname>proxy</fieldname>
			<description>Enter the proxy here.</description>
			<type>input</type>
			<value></value>			
		</field>
		<field>
			<fielddescr>Expire-seconds</fielddescr>
			<fieldname>expire-seconds</fieldname>
			<description>Enter the expire-seconds here. Example: 600</description>
			<type>input</type>
			<value>600</value>
		</field>
		<field>
			<fielddescr>Register</fielddescr>
			<fieldname>register</fieldname>
			<description>Choose whether to register.</description>
			<type>select</type>
			<options>
				<option>
					<name>True</name>
					<value>true</value>
				</option>
				<option>
					<name>False</name>
					<value>false</value>
				</option>
			</options>
		</field>
		<field>
			<fielddescr>Register-transport</fielddescr>
			<fieldname>register-transport</fieldname>
			<description>Choose whether to register-transport.</description>
			<type>select</type>
			<options>
				<option>
					<name></name>
					<value></value>
				</option>			
				<option>
					<name>udp</name>
					<value>udp</value>
				</option>
				<option>
					<name>tcp</name>
					<value>tcp</value>
				</option>
			</options>
		</field>		  
		<field>
			<fielddescr>Retry-seconds</fielddescr>
			<fieldname>retry-seconds</fieldname>
			<description>Enter the retry_seconds here. Example: 30</description>
			<type>input</type>
			<value>30</value>
		</field>
		<field>
			<fielddescr>Extension</fielddescr>
			<fieldname>extension</fieldname>
			<description>Enter the extension here.</description>
			<type>input</type>
			<value></value>
		</field>
		<field>
			<fielddescr>Context</fielddescr>
			<fieldname>context</fieldname>
			<description>Enter the context here. Example: public</description>
			<type>input</type>
			<value>public</value>
		</field>
    <field>
			<fielddescr>Caller-id-in-from</fielddescr>
			<fieldname>caller-id-in-from</fieldname>
			<description>Choose caller-id-in-from.</description>
			<type>select</type>
			<options>
				<option>
					<name></name>
					<value></value>
				</option>
				<option>
					<name>True</name>
					<value>true</value>
				</option>
				<option>
					<name>False</name>
					<value>false</value>
				</option>
			</options>
		</field>
		<field>
			<fielddescr>Supress-cng</fielddescr>
			<fieldname>supress-cng</fieldname>
			<description>Choose whether to supress-cng.</description>
			<type>select</type>
			<options>
				<option>
					<name></name>
					<value></value>
				</option>
				<option>
					<name>True</name>
					<value>true</value>
				</option>
				<option>
					<name>False</name>
					<value>false</value>
				</option>
			</options>
		</field> 		
		<field>
			<fielddescr>Gateway Description</fielddescr>
			<fieldname>description</fieldname>
			<description>Enter the description of the gateway here.</description>
			<type>input</type>
			<value></value>			
		</field>
	</fields>
	<custom_add_php_command>
	</custom_add_php_command>
	<custom_php_resync_config_command>
	    sync_package_freeswitch_gateways();
	</custom_php_resync_config_command>
	<custom_delete_php_command>    
      sync_package_freeswitch_gateways();
	</custom_delete_php_command>
	<custom_php_deinstall_command>
	</custom_php_deinstall_command>	
</packagegui>

=== 007au/pfsense-packages/packages/openbgpd/openbgpd_neighbors.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    openbgpd_neighbors.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Scott Ullrich (sullrich@gmail.com)
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>OpenBGPDNeighbors</name>
	<version>1</version>
	<title>Services: OpenBGPD Neighbors</title>
	<include_file>/usr/local/pkg/openbgpd.inc</include_file>
	<tabs>
		<tab>
			<text>Settings</text>
			<url>/pkg_edit.php?xml=openbgpd.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Neighbors</text>
			<url>/pkg.php?xml=openbgpd_neighbors.xml</url>
			<active/>
		</tab>
		<tab>
			<text>Groups</text>
			<url>/pkg.php?xml=openbgpd_groups.xml</url>
		</tab>
		<tab>
			<text>Status</text>
			<url>/openbgpd_status.php</url>
		</tab>
	</tabs>
	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>descr</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Neighbor</fielddescr>
			<fieldname>neighbor</fieldname>
		</columnitem>
	</adddeleteeditpagefields>
	<fields>
		<field>
			<fielddescr>Description</fielddescr>
			<fieldname>descr</fieldname>
			<description></description>
			<type>input</type>
			<size>80</size>
		</field>
		<field>
			<fielddescr>Neighbor</fielddescr>
			<fieldname>neighbor</fieldname>
			<description>Neighbor IP address</description>
			<type>input</type>
			<size>25</size>
		</field>
		<field>
			<fielddescr>Group</fielddescr>
			<fieldname>groupname</fieldname>
			<description>Add neighbor to BGP group.</description>
			<type>select</type>
			<options>
				<option>
					<name>NAME</name>
					<value>VALUE</value>
				</option>
			</options>
		</field>
		<field>
			<fielddescr>none</fielddescr>
			<fieldname>none</fieldname>
		    <type>rowhelper</type>
		    <rowhelper>
				<rowhelperfield>
				    <fielddescr>Paramaters</fielddescr>
				    <fieldname>paramaters</fieldname>
				    <description>Neighbor settings.  Items ending with a X require a value.  Leave the items without a trailing X's value blank.</description>
				    <type>select</type>
					<options>
						<option><name>Announce all</name><value>announce all</value></option>
						<option><name>Announce none</name><value>announce none</value></option>
						<option><name>Announce self</name><value>announce self</value></option>
						<option><name>Announce default-route</name><value>announce default-route</value></option>
						<option><name>Metric X</name><value>set metric</value></option>
						<option><name>Multihop X</name><value>multihop</value></option>
						<option><name>Localpref X</name><value>set localpref</value></option>
						<option><name>Softreconfig in yes</name><value>softreconfig in yes</value></option>
						<option><name>Softreconfig in no</name><value>softreconfig in no</value></option>
						<option><name>Softreconfig out yes</name><value>softreconfig out yes</value></option>
						<option><name>Softreconfig out no</name><value>softreconfig out no</value></option>
						<option><name>Tcp md5sig password X</name><value>tcp md5sig password</value></option>
						<option><name>Local address X</name><value>local-address</value></option>			
					</options>
				</rowhelperfield>
				<rowhelperfield>
				    <fielddescr>Value</fielddescr>
				    <fieldname>parmvalue</fieldname>
				    <description>When the WAN MS ping time is surpassed, item will failover to next host</description>
				    <type>input</type>
				    <size>15</size>
				</rowhelperfield>
		    </rowhelper>
		</field>
	</fields>
	<custom_php_command_before_form>
		$newoptions = array();
		$new_groups = array();
		foreach($config['installedpackages']['openbgpdgroups']['config'] as $item) 
    		    $new_groups[] = $item['name'];  
		$counter = 0;  		    
		foreach($new_groups as $group) {
			$newoptions['option'][$counter]['name'] = $group;
			$newoptions['option'][$counter]['value'] = $group;
			$counter++;
		}	
		$newoptions['option'][$counter]['name'] = "";
		$newoptions['option'][$counter]['value'] = "";		
		$pkg['fields']['field'][2]['options'] = $newoptions; 
		$counter = 0;
		foreach($pkg['fields']['field'] as $field) {
			if($field['name'] == "group") {
				$foundgroupid = $counter;
				echo "found it: $counter";
			}
			$counter++;
		}

	</custom_php_command_before_form>
	<custom_php_deinstall_command>
	</custom_php_deinstall_command>
	<custom_php_resync_config_command>
		openbgpd_install_conf();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/packages/squidGuard/squidguard_time.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
	<description>Describe your package here</description>
	<requirements>Describe your package requirements here</requirements>
	<faq>Currently there are no FAQ items provided.</faq>

	<name>squidguardtime</name>
	<version>none</version>
	<title>Proxy server filter SquidGuard: Times</title>
	<include_file>squidguard.inc</include_file>

	<delete_string>A proxy server user has been deleted.</delete_string>
	<addedit_string>A proxy server user has been created/modified.</addedit_string>

	<tabs>
		<tab>
			<text>General settings</text>
			<url>/pkg_edit.php?xml=squidguard.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Default</text>
			<url>/pkg_edit.php?xml=squidguard_default.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>ACL</text>
			<url>/pkg.php?xml=squidguard_acl.xml</url>
		</tab>
		<tab>
			<text>Sources</text>
			<url>/pkg.php?xml=squidguard_src.xml</url>
		</tab>
		<tab>
			<text>Destinations</text>
			<url>/pkg.php?xml=squidguard_dest.xml</url>			
		</tab>
		<tab>
			<text>Times</text>
			<url>/pkg.php?xml=squidguard_time.xml</url>
			<active/>
		</tab>
		<tab>
			<text>Rewrites</text>
			<url>/pkg.php?xml=squidguard_rewr.xml</url>
		</tab>
		<tab>
			<text>Log</text>
			<url>/pkg_edit.php?xml=squidguard_log.xml</url>
		</tab>
	</tabs>
	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Timename</fielddescr>
			<fieldname>name</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
		</columnitem>
	</adddeleteeditpagefields>
	<fields>
		<field>
			<fielddescr>Name</fielddescr>
			<fieldname>name</fieldname>
			<description>Enter the time name here.</description>
			<type>input</type>
			<size>80</size>
			<required/>
		</field>
		<field>
  			<type>rowhelper</type> 
			<fielddescr>Values</fielddescr>
 			<rowhelper>
 				<rowhelperfield>
					<fielddescr>Time type</fielddescr>
					<fieldname>timetype</fieldname>
					<description></description>
					<type>select</type>
					<value>weekly</value>
					<options>
			    			<option><name>Weekly</name><value>weekly</value></option>
			    			<option><name>Date</name><value>date</value></option>
					</options> 
  				</rowhelperfield>
 				<rowhelperfield>
					<fielddescr>Days</fielddescr>
					<fieldname>timedays</fieldname>
					<description></description>
					<type>select</type>
					<value>*</value>
					<options>
			    			<option><name>all</name><value>*</value></option>
			    			<option><name>mon</name><value>mon</value></option>
			    			<option><name>tue</name><value>tue</value></option>
			    			<option><name>wed</name><value>wed</value></option>
			    			<option><name>thu</name><value>thu</value></option>
			    			<option><name>fri</name><value>fri</value></option>
			    			<option><name>sat</name><value>sat</value></option>
			    			<option><name>sun</name><value>sun</value></option>
					</options> 
  				</rowhelperfield>
 				<rowhelperfield>
  					<fielddescr>Date or Date range</fielddescr> 
  					<fieldname>daterange</fieldname> 
  					<description>00:00-08:00 15:00-21:00 Format: *.01.01</description> 
  					<type>input</type> 
					<size>40</size>
  				</rowhelperfield>
 				<rowhelperfield>
  					<fielddescr>Time range</fielddescr> 
  					<fieldname>timerange</fieldname> 
  					<description>00:00-08:00</description> 
  					<type>input</type> 
					<size>20</size>
  				</rowhelperfield>
  			</rowhelper>
		</field>
		<field>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
			<description>You may enter a description here for your reference (not parsed).</description>
			<type>input</type>
			<size>80</size>
		</field>
	</fields>
	<custom_php_after_form_command> 
               squidGuard_print_javascript();
	</custom_php_after_form_command>
	<custom_php_validation_command>
		squidguard_validate_times(&amp;$_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_php_resync_config_command>
//		squidguard_resync_time();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/packages/freeradius.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 to whom it may belong
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>freeradius</name>
	<version>1.1.2</version>
	<title>FreeRADIUS: Users</title>
	<include_file>freeradius.inc</include_file>
	<menu>
		<name>FreeRADIUS</name>
		<tooltiptext>Modify FreeRADIUS users, clients, and settings.</tooltiptext>
		<section>Services</section>
		<url>/pkg.php?xml=freeradius.xml</url>
	</menu>
	<service>
		<name>FreeRADIUS</name>
		<rcfile>radiusd.sh</rcfile>
		<executable>radiusd</executable>
		<description>The FreeRADIUS daemon.</description>
	</service>

	<tabs>
		<tab>
			<text>Users</text>
			<url>/pkg.php?xml=freeradius.xml</url>
			<active/>
		</tab>
		<tab>
			<text>Clients</text>
			<url>/pkg.php?xml=freeradiusclients.xml</url>
		</tab>
		<tab>
			<text>Settings</text>
			<url>/pkg_edit.php?xml=freeradiussettings.xml&amp;id=0</url>
		</tab>
	</tabs>

	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Username</fielddescr>
			<fieldname>username</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
		</columnitem>
	</adddeleteeditpagefields>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>077</chmod>		
		<item>http://www.pfsense.org/packages/config/freeradiusclients.xml</item>
	</additional_files_needed>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>077</chmod>		
		<item>http://www.pfsense.org/packages/config/freeradiussettings.xml</item>
	</additional_files_needed>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>077</chmod>	
		<item>http://www.pfsense.org/packages/config/freeradius.inc</item>
	</additional_files_needed>
	<fields>
		<field>
			<fielddescr>Username</fielddescr>
			<fieldname>username</fieldname>
			<description>Enter the username.</description>
			<type>input</type>
			<required/>
		</field>
		<field>
			<fielddescr>Password</fielddescr>
			<fieldname>password</fieldname>
			<description>Enter the password for this username.</description>
			<type>password</type>
			<required/>
		</field>
		<field>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
			<description>You may enter a description here for your reference (not parsed).</description>
			<type>input</type>
		</field>
	</fields>
	<custom_delete_php_command>
		freeradius_users_resync();
	</custom_delete_php_command>
	<custom_php_resync_config_command>
		freeradius_users_resync();
	</custom_php_resync_config_command>
	<custom_php_install_command>
		freeradius_install_command();
	</custom_php_install_command>
	<custom_php_deinstall_command>	
		freeradius_deinstall_command();
	</custom_php_deinstall_command>
</packagegui>
