=== 007au/pfsense-packages/packages/schema/packages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/* $Id$ */
/* ========================================================================== */
/*
    package.dtd
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
-->
<!ELEMENT version (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT tooltiptext (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT savetext (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT tabs ((tab*))>
<!ELEMENT tab ((text, url, active?))>
<!ELEMENT service ((name, rcfile, executable?))>
<!ELEMENT section (#PCDATA)>
<!ELEMENT requirements (#PCDATA)>
<!ELEMENT rcfile (#PCDATA)>
<!ELEMENT executable (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT packagegui ((copyright, description, requirements, faq, name, version, title, note?, savetext?, aftersaveredirect?, include_file?, menu*, service?, tabs?, configpath?, adddeleteeditpagefields?, additional_files_needed*, fields?, custom_php_global_functions?, custom_php_command_before_form?, custom_delete_php_command?, custom_add_php_command?, custom_php_resync_config_command?, custom_php_validation_command?, custom_add_php_command_late?, start_command?, restart_command?, custom_php_after_form_command?, custom_php_resync_config_command?, custom_php_install_command?, custom_php_deinstall_command?))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT menu ((name, tooltiptext?, section?, configfile?, url?))>
<!ELEMENT item (#PCDATA)>
<!ELEMENT include_file (#PCDATA)>
<!ELEMENT aftersaveredirect (#PCDATA)>
<!ELEMENT faq (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT donotdisable (#PCDATA)>
<!ELEMENT enablefields (#PCDATA)>
<!ELEMENT required EMPTY>
<!ELEMENT multiple (#PCDATA)>
<!ELEMENT default_value (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT options ((option+))>
<!ELEMENT option ((name, value))>
<!ELEMENT fields ((field+))>
<!ELEMENT fieldname (#PCDATA)>
<!ELEMENT fielddescr (#PCDATA)>
<!ELEMENT field ((fielddescr, fieldname, description?, type, donotdisable?, enablefields?, size?, required?, default_value?, value?, multiple?, options?))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT custom_php_global_functions (#PCDATA)>
<!ELEMENT custom_php_command_before_form (#PCDATA)>
<!ELEMENT custom_delete_php_command (#PCDATA)>
<!ELEMENT custom_add_php_command (#PCDATA)>
<!ELEMENT custom_php_resync_config_command (#PCDATA)>
<!ELEMENT custom_php_validation_command (#PCDATA)>
<!ELEMENT custom_add_php_command_late (#PCDATA)>
<!ELEMENT start_command (#PCDATA)>
<!ELEMENT restart_command (#PCDATA)>
<!ELEMENT custom_php_after_form_command (#PCDATA)>
<!ELEMENT custom_php_install_command (#PCDATA)>
<!ELEMENT custom_php_deinstall_command (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT configpath (#PCDATA)>
<!ELEMENT configfile (#PCDATA)>
<!ELEMENT chmod (#PCDATA)>
<!ELEMENT columnitem ((fielddescr, fieldname))>
<!ELEMENT adddeleteeditpagefields ((columnitem+))>
<!ELEMENT additional_files_needed ((prefix, chmod, item))>
<!ELEMENT active EMPTY>

=== 007au/pfsense-packages/packages/squidGuard/squidguard_default.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>

	<name>squidguarddefault</name>
	<version>none</version>
	<title>Proxy Content filter SquidGuard: Default</title>
	<include_file>/usr/local/pkg/squidguard.inc</include_file>

	<tabs>
		<tab>
			<text>General settings</text>
			<url>/pkg_edit.php?xml=squidguard.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Default</text>
			<url>/pkg_edit.php?xml=squidguard_default.xml&amp;id=0</url>
			<active/>
		</tab>
		<tab>
			<text>ACL</text>
			<url>/pkg.php?xml=squidguard_acl.xml</url>
		</tab>
		<tab>
			<text>Destinations</text>
			<url>/pkg.php?xml=squidguard_dest.xml</url>			
		</tab>
		<tab>
			<text>Times</text>
			<url>/pkg.php?xml=squidguard_time.xml</url>
		</tab>
		<tab>
			<text>Rewrites</text>
			<url>/pkg.php?xml=squidguard_rewr.xml</url>
		</tab>
		<tab>
			<text>Log</text>
			<url>/pkg_edit.php?xml=squidguard_log.xml</url>
		</tab>
	</tabs>
	
	<fields>		
		<field>
			<fielddescr>Default destination</fielddescr>
			<fieldname>dest</fieldname>
			<description></description>
			<type>input</type>
			<size>100</size>
		</field>
		<field>
			<fielddescr>Not to allow IP addresses in URL</fielddescr>
			<fieldname>notallowingip</fieldname>
			<description>
				To make sure that people don't bypass the URL filter 
				by simply using the IP addresses instead of the fully qualified domain names, you can check this option.   
			</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Default Redirect</fielddescr>
			<fieldname>redirect</fieldname>
			<description>
				Enter redirection URL, Tag or Error page code for this rule, or leave blank. &lt;br&gt;
				Supported URL's: 'http://myurl', 'https://myurl'. &lt;br&gt;
				Supported tags: 'blank', 'blank_img'. &lt;br&gt;
				Supported error page codes: 3xx, 4xx, 5xx. Format: 'code' or 'code[space]reason message'.
			</description>
			<type>textarea</type>
			<cols>65</cols>
			<rows>2</rows>
		</field>
		<field>
			<fielddescr>Default Rewrite</fielddescr>
			<fieldname>rewrite</fieldname>
			<description>Enter rewrite condition name for this rule, or leave blank.</description>
			<type>select</type>
		</field>
		<field>
			<fielddescr>Enable log</fielddescr>
			<fieldname>enablelog</fieldname>
			<description>Check this for enable log.</description>
			<type>checkbox</type>
		</field>
	</fields>

	<custom_php_validation_command>
		squidguard_validate_acl(&amp;$_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_php_command_before_form>
		squidguard_before_form_acl(&amp;$pkg, false);
	</custom_php_command_before_form>
	<custom_php_after_form_command> 
        squidGuard_print_javascript();
	</custom_php_after_form_command>
	<custom_add_php_command/>
	<custom_php_resync_config_command>
//		squidguard_resync();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/packages/frickin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 to whom it may belong
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>frickin</name>
	<version>1.2</version>
	<title>none</title>
	<configpath>installedpackages->package->$packagename->configuration->settings</configpath>
	<additional_files_needed>
		<prefix>/usr/local/bin/</prefix>
		<chmod>0755</chmod>
		<item>http://www.pfsense.com/packages/All/frickin</item>
        </additional_files_needed>
	<custom_php_install_command>
	    $fout = fopen("/usr/local/etc/rc.d/frickin.sh", "w");
	    fwrite($fout, "#!/bin/sh\n# This package was automatically generated\n# by the pfSense package system.\n\n");
            fwrite($fout, "# PACKAGE: Frickin Proxy\n");
            fwrite($fout, "# EXECUTABLE: frickin\n");
	    fwrite($fout, "/usr/local/bin/frickin");
	    fwrite($fout, " -s 127.0.0.1");
	    fwrite($fout, " -c 20");
	    fwrite($fout, " &amp;\n");
	    fclose($fout);
	    mwexec("/usr/bin/killall frickin");
	    mwexec("chmod a+rx /usr/local/etc/rc.d/frickin.sh");
	    mwexec("/usr/local/etc/rc.d/frickin.sh");
	</custom_php_install_command>
	<custom_php_deinstall_command>
	    unlink_if_exists("/usr/local/etc/rc.d/frickin.sh");
	    unlink_if_exists("/usr/local/bin/frickin");
	</custom_php_deinstall_command>
</packagegui>

=== 007au/pfsense-packages/packages/autoconfigbackup/autoconfigbackup.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
	<copyright>
        <![CDATA[
		/* $Id$ */
		/*
		   autoconfigbackup.xml 
		   part of pfSense (http://www.pfSense.com)
		   Copyright (C) 2008 BSD Perimeter
		   All rights reserved.
		                                                                             */
		   Redistribution and use in source and binary forms, with or without
		   modification, are permitted provided that the following conditions are met:

		    1. Redistributions of source code must retain the above copyright notice,
		       this list of conditions and the following disclaimer.

		    2. Redistributions in binary form must reproduce the above copyright
		       notice, this list of conditions and the following disclaimer in the
		       documentation and/or other materials provided with the distribution.

		   THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
		   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
		   AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
		   AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
		   OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
		   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
		   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
		   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
		   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
		   POSSIBILITY OF SUCH DAMAGE.
		*/
        ]]>
	</copyright>
    <description>Automatically backs up your pfSense configuration.  All contents are encrypted on the server.  Requires pfSense Premium Support Portal Subscription from http://portal.pfsense.org</description>
    <requirements>pfSense Premium Support Portal</requirements>
	<name>AutoConfigBackup</name>
	<version>1.0</version>
	<title>Diagnostics: Auto Configuration Backup</title>
	<savetext>Change</savetext>
	<includefile>/usr/local/pkg/autoconfigbackup.inc</includefile>
	<aftersaveredirect>pkg_edit.php?xml=autoconfigbackup.xml&amp;id=0</aftersaveredirect>
	<menu>
		<name>AutoConfigBackup</name>
		<tooltiptext>Set autoconfigbackup settings such as password and port.</tooltiptext>
		<section>Diagnostics</section>
		<url>/pkg_edit.php?xml=autoconfigbackup.xml&amp;id=0</url>
	</menu>
	<additional_files_needed>
	    <prefix>/usr/local/pkg/pf/</prefix>
	    <chmod>0755</chmod>
		<item>http://www.pfsense.com/packages/config/autoconfigbackup/upload_config_filter.php</item>
	</additional_files_needed>
	<additional_files_needed>
	    <prefix>/usr/local/www/</prefix>
	    <chmod>0755</chmod>
		<item>http://www.pfsense.com/packages/config/autoconfigbackup/autoconfigbackup.php</item>
	</additional_files_needed>
	<additional_files_needed>
	    <prefix>/usr/local/pkg/</prefix>
	    <chmod>0755</chmod>
		<item>http://www.pfsense.com/packages/config/autoconfigbackup/autoconfigbackup.inc</item>
	</additional_files_needed>
	<tabs>
		<tab>
			<text>Settings</text>
			<url>/pkg_edit.php?xml=autoconfigbackup.xml&amp;id=0</url>
			<active/>
		</tab>
		<tab>
			<text>Restore</text>
			<url>/autoconfigbackup.php</url>
		</tab>
	</tabs>
	<fields>
		<field>
			<fielddescr>Subscription Username</fielddescr>
			<fieldname>username</fieldname>
			<description>Enter the username for the Automatic Configuration Backup Web GUI.  Minimum 6 characters.</description>
			<type>intput</type>
		</field>
		<field>
			<fielddescr>Subscription Password</fielddescr>
			<fieldname>password</fieldname>
			<description>Enter the password for the Automatic Configuration Backup Web GUI.  Minimum 6 characters.</description>
			<type>password</type>
		</field>
		<field>
			<fielddescr>Enter Password again</fielddescr>
			<fieldname>passwordagain</fieldname>
			<type>password</type>
		</field>
		<field>
			<fielddescr>Encryption Password</fielddescr>
			<fieldname>crypto_password</fieldname>
			<type>password</type>
		</field>
    </fields>
	<custom_php_validation_command>
		custom_php_validation_command($_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_php_global_functions>
	</custom_php_global_functions>
	<custom_add_php_command>
	</custom_add_php_command>
	<custom_php_resync_config_command>
	</custom_php_resync_config_command>
	<custom_php_install_command>
	</custom_php_install_command>
	<custom_php_deinstall_command>
	</custom_php_deinstall_command>
</packagegui>

=== 007au/pfsense-packages/packages/p3scan-pf/p3scan-pf-msg.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
  <description>Describe your package here</description>
  <requirements>Describe your package requirements here</requirements>
  <faq>Currently there are no FAQ items provided.</faq>
    <!-- change this if configpath works -->
  <name>p3scanpfmsg</name>
  <version>1.0</version>
  <title>Services: POP3 Proxy: Message Processing</title>
  <note>
    This &lt;acronym title=&quot;Hypertext Markup Language&quot;&gt;HTML&lt;/acronym&gt; page uses default values, hence even if each field is 
    set, you are still required to save this page if you are editing this page
    for the very first time!
  </note>
  <aftersaveredirect>pkg_edit.php?xml=p3scan-pf-msg.xml&amp;id=0</aftersaveredirect>
  <include_file>p3scan-pf.inc</include_file>
  <tabs>
    <tab>
      <text>Daemon Settings</text>
      <url>/pkg_edit.php?xml=p3scan-pf.xml&amp;id=0</url>
    </tab>
    <tab>
      <text>Transparent Proxy Exclusion</text>
      <url>/pkg.php?xml=p3scan-pf-transex.xml</url>
    </tab>
    <tab>
      <text>Message Processing</text>
      <url>/pkg_edit.php?xml=p3scan-pf-msg.xml&amp;id=0</url>
      <active />
    </tab>
    <tab>
      <text>Emergency Contact</text>
      <url>/pkg.php?xml=p3scan-pf-emer.xml</url>
    </tab>
    <tab>
      <text>Virus Scanner Settings</text>
      <url>/pkg_edit.php?xml=p3scan-pf-vir.xml&amp;id=0</url>
    </tab>
    <tab>
      <text>SPAM Settings</text>
      <url>/pkg_edit.php?xml=p3scan-pf-spam.xml&amp;id=0</url>
    </tab>
  </tabs>
  <!-- 
    configpath gets expanded out automatically and config items
    will be stored in that location
  -->
  <configpath>['installedpackages']['p3scanpf']['config']['messaging']</configpath>
  <!--
    fields gets invoked when the user adds or edits a item. The following items
    will be parsed and rendered for the user as a gui with input, and selectboxes.
  -->
  <fields>
    <field>
      <fielddescr>Just Delete</fielddescr>
      <fieldname>justdelete</fieldname>
      <description>
        Instead of keeping an infected message in the Virus Directory, delete it 
        after reporting it to the user.
      </description>
      <type>checkbox</type>
      <donotdisable>true</donotdisable>
    </field>
    <field>
      <fielddescr>Bytes Free</fielddescr>
      <fieldname>bytesfree</fieldname>
      <description>The number of KB's there must be free before processing any mail.</description>
      <type>input</type>
      <required />
      <default_value>10000</default_value>
    </field>
    <field>
      <fielddescr>Broken Email Clients</fielddescr>
      <fieldname>brokenec</fieldname>
      <description>
        Some email clients may require special processing.
      </description>
      <type>checkbox</type>
      <donotdisable>true</donotdisable>
    </field>
    <field>
      <fielddescr>ISP Spam</fielddescr>
      <fieldname>ispspam</fieldname>
      <description>
        This option allows you to set the string your &lt;acronym title=&quot;Internet Service Provider&quot;&gt;ISP&lt;/acronym&gt; uses if it processes 
        your email for SPAM. Leave this field blank if you are not going to use 
        this option.
      </description>
      <type>input</type> 
      <default_value>-- Spam --</default_value>
    </field>
    <field>
      <fielddescr>Subject</fielddescr>
      <fieldname>subject</fieldname>
      <description>
        This option can be used to change the default subject line when 
        reporting a virus infected message.
      </description>
      <type>input</type>
      <size>60</size>
      <required />
      <default_value>Subject: "[Virus] found in a mail to you:" &lt;virus name&gt;</default_value>
    </field>
    <field>
      <fielddescr>Notify</fielddescr>
      <fieldname>notify</fieldname>
      <description>
        This option can be used to change the default file deleted notification 
        that is displayed in the virus notification message when the 
        &quot;justdelete&quot; option is used.
      </description>
      <type>input</type>
      <size>60</size>
      <required />
      <default_value>Per instruction, the message has been deleted.</default_value>
    </field>
    <field>
      <fielddescr>SMTP Reject</fielddescr>
      <fieldname>smtpreject</fieldname>
      <description>
        This option can be used to change the default &lt;acronym title=&quot;Simple Mail Transfer Protocol&quot;&gt;SMTP&lt;/acronym&gt; Reject message that 
        is sent to the client in the event a message is rejected due to a virus. 
        The error message will have a prefix of &quot;554&quot;.
      </description>
      <type>input</type>
      <size>60</size>
      <required />
      <default_value>Virus detected! P3scan rejected message!</default_value>
    </field>
    <field>
      <fielddescr>Check SMTP size</fielddescr>
      <fieldname>checksize</fieldname>
      <description>
        This option can be used to set the maximum message size (in KBytes) 
        that p3scan will use to determine if it should scan an smtp submission. 
        Leave this field blank if you are not going to use this option.
      </description>
      <type>input</type>
      <default_value>1024</default_value>
    </field>
    <field>
      <fielddescr>Footer</fielddescr>
      <fieldname>footer</fieldname>
      <description>
        This option is used to add the virus definition info from your scanner 
        to an SMTP message. Leave this field blank if you are not going to use 
        this option.
      </description>
      <type>input</type>
      <size>40</size>
      <default_value>/usr/local/bin/clamdscan -V</default_value>
    </field>
  </fields>
  <!--
    Arbitrary PHP Code, that gets executed if a certain event gets triggered.
  -->
  <custom_php_resync_config_command> 
    sync_package_p3scan();
  </custom_php_resync_config_command>
</packagegui>
