=== 007au/pfsense-packages/config/schema/packages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ...................................................................... -->
<!-- pfSense Package DTD V1.0 ............................................. -->
<!-- File package.dtd ..................................................... -->
<!--
/* $Id$ */
/* ========================================================================== */
/*
    package.dtd
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
-->
<!--
  |
  | May be parsed using http://dtdparse.sourceforge.net/ to generate an
  | HTML document that describes this DTD.
  |
-->
<!-- Indicates the version of a package -->
<!ELEMENT version (#PCDATA)>
<!-- Indicates where to get more informations about this package -->
<!ELEMENT url (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT depends_on_service (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT tooltiptext (#PCDATA)>
<!-- The title of a particular package -->
<!ELEMENT title (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT textneeded (#PCDATA)>
<!-- Categroy of a particular package (e.g. System) -->
<!ELEMENT category (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT note (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT savetext (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT preoutput (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT donotsave (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT text (#PCDATA)>
<!-- Container element. Contains several tab elements -->
<!ELEMENT tabs ((tab*))>
<!-- A specific tab that is part of a tab pane -->
<!ELEMENT tab ((text, url, active?))>
<!-- A service that may be executed while starting the system -->
<!ELEMENT service ((name, rcfile?, executable?, description?))>
<!-- needs to be documented -->
<!ELEMENT section (#PCDATA)>
<!-- Indicates what particular kind of components may be required to run this package -->
<!ELEMENT requirements (#PCDATA)>
<!-- Shell script that is beeing used to start and stop a service -->
<!ELEMENT rcfile (#PCDATA)>
<!-- Executable that represents a service -->
<!ELEMENT executable (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT prefix (#PCDATA)>
<!-- Root node of a package definition. Container element -->
<!ELEMENT packagegui ((copyright, description, requirements, faq, name, version, title, category?, note?, savetext?, preoutput?, donotsave?, aftersaveredirect?, include_file?, backup_file?, delete_string?, addedit_string?, menu*, service*, modify_system?, tabs?, configpath?, adddeleteeditpagefields?, additional_files_needed*, fields?, custom_php_global_functions?, custom_php_command_before_form?, custom_delete_php_command?, custom_add_php_command?, custom_php_resync_config_command?, custom_php_validation_command?, custom_add_php_command_late?, start_command?, restart_command?, process_kill_command?, custom_php_after_form_command?, custom_php_resync_config_command?, custom_php_install_command?, custom_php_deinstall_command?, custom_php_before_form_command?, custom_php_after_head_command?, templates?))>
<!-- A particular name -->
<!ELEMENT name (#PCDATA)>
<!-- Menu item. Container element -->
<!ELEMENT menu ((name, tooltiptext?, section?, configfile?, url?, depends_on_service?))>
<!-- needs to be documented -->
<!ELEMENT modifyitem ((modifyfilename?, textneeded?))>
<!-- needs to be documented -->
<!ELEMENT item (#PCDATA)>
<!-- A PHP file that needs to be included prior to executing arbitrary PHP code -->
<!ELEMENT include_file (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT backup_file (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT delete_string (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT addedit_string (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT aftersaveredirect (#PCDATA)>
<!-- FAQ items or an URL that points to certain FAQ items -->
<!ELEMENT faq (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT modifyfilename (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT modify_system ((modifyitem+))>
<!-- needs to be documented -->
<!ELEMENT rowhelperfield ((fielddescr, fieldname, description, type, size?, options?))>
<!-- needs to be documented -->
<!ELEMENT rowhelper ((rowhelperfield+))>
<!-- needs to be documented -->
<!ELEMENT size (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT donotdisable (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT enablefields (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT required EMPTY>
<!-- needs to be documented -->
<!ELEMENT multiple (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT default_value (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT value (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT type (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT cols (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT rows (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT combinefieldsbegin (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT combinefieldsend (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT dontdisplayname (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT dontcombinecells (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT onchange (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT encoding (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT typehint (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT options ((option+))>
<!-- needs to be documented -->
<!ELEMENT option ((name, value))>
<!-- needs to be documented -->
<!ELEMENT fields ((field*))>
<!-- needs to be documented -->
<!ELEMENT filename (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT fieldname (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT fielddescr (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT validationtype (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT field ((fielddescr, fieldname, description?, type, donotdisable?, enablefields?, size?, required?, default_value?, value?, multiple?, options?, cols?, rows?, typehint?, onchange?, encoding?, combinefieldsend?, combinefieldsbegin?, rowhelper?, dontdisplayname?, dontcombinecells?, validationtype?))>
<!-- needs to be documented -->
<!ELEMENT description (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_global_functions (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_command_before_form (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_delete_php_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_add_php_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_resync_config_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_validation_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_add_php_command_late (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT process_kill_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT start_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT restart_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_after_form_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_install_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_deinstall_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_after_head_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_before_form_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT copyright (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT configpath (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT configfile (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT chmod (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT columnitem ((fielddescr, fieldname))>
<!-- needs to be documented -->
<!ELEMENT adddeleteeditpagefields ((columnitem+))>
<!-- needs to be documented -->
<!ELEMENT additional_files_needed ((prefix?, chmod?, item))>
<!-- needs to be documented -->
<!ELEMENT active EMPTY>
<!-- needs to be documented -->
<!ELEMENT templates ((template+))>
<!-- needs to be documented -->
<!ELEMENT templatecontents (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT template ((filename, templatecontents))>
<!-- End of pfSense package DTD V1.0 ...................................... -->
<!-- ...................................................................... -->

=== 007au/pfsense-packages/config/squid-reverse/squid_reverse.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 to whom it may belong
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>squidreverse</name>
	<version>none</version>
	<title>Proxy server: Reverse Proxy</title>
	<include_file>squid.inc</include_file>
	<tabs>
		<tab>
			<text>General</text>
			<url>/pkg_edit.php?xml=squid.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Upstream Proxy</text>
			<url>/pkg_edit.php?xml=squid_upstream.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Cache Mgmt</text>
			<url>/pkg_edit.php?xml=squid_cache.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Access Control</text>
			<url>/pkg_edit.php?xml=squid_nac.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Traffic Mgmt</text>
			<url>/pkg_edit.php?xml=squid_traffic.xml&amp;id=0</url>
    </tab>
		<tab>
			<text>Reverse Proxy</text>
			<url>/pkg_edit.php?xml=squid_reverse.xml&amp;id=0</url>
			<active/>
		</tab>
		<tab>
			<text>Reverse Settings</text>
			<url>/pkg_edit.php?xml=squid_reverse.xml&amp;id=0</url>
			<active/>
		</tab>		
		<tab>
			<text>Auth Settings</text>
			<url>/pkg_edit.php?xml=squid_auth.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Local Users</text>
			<url>/pkg.php?xml=squid_users.xml</url>
		</tab>
	</tabs>
	<fields>
		<field>
			<fielddescr>Reverse Proxy interface</fielddescr>
			<fieldname>reverse_interface</fieldname>
			<description>The interface(s) the reverse-proxy server will bind to.</description>
			<type>interfaces_selection</type>
			<required/>
			<default_value>wan</default_value>
			<multiple/>
		</field>
		<field>
			<fielddescr>external FQDN</fielddescr>
			<fieldname>reverse_external_fqdn</fieldname>
			<description>The external full-qualified-domain-name of the WAN address.</description>
			<type>input</type>
			<required/>
			<size>80</size>
		</field>
		<field>
			<fielddescr>Enable HTTP reverse mode.</fielddescr>
			<fieldname>reverse_http</fieldname>
			<description>If this field is checked, the proxy-server will act in HTTP reverse mode.</description>
			<type>checkbox</type>
			<enablefields>reverse_http_port,reverse_http_defsite</enablefields>			
			<required/>
			<default_value>off</default_value>
		</field>
		<field>
			<fielddescr>reverse HTTP port</fielddescr>
			<fieldname>reverse_http_port</fieldname>
			<description>This is the port the HTTP reverse-proxy will listen on. (leave empty to use 80)</description>
			<type>input</type>
			<size>5</size>
			<default_value>80</default_value>
		</field>
		<field>
			<fielddescr>reverse HTTP default site</fielddescr>
			<fieldname>reverse_http_defsite</fieldname>
			<description>This is the HTTP reverse default site. (leave empty to use the external fqdn)</description>
			<type>input</type>
			<size>60</size>
			<default_value>localhost</default_value>
		</field>		

		<field>
			<fielddescr>Enable HTTPS reverse mode.</fielddescr>
			<fieldname>reverse_https</fieldname>
			<description>If this field is checked, the proxy-server will act in HTTPS reverse mode.</description>
			<type>checkbox</type>
			<enablefields>reverse_https_port,reverse_ssl_cert,reverse_https_defsite,ignore_ssl_valid</enablefields>			
			<required/>
			<default_value>off</default_value>
		</field>
		<field>
			<fielddescr>reverse HTTPS port</fielddescr>
			<fieldname>reverse_https_port</fieldname>
			<description>This is the port the HTTPS reverse-proxy will listen on. (leave empty to use 443)</description>
			<type>input</type>
			<size>5</size>
			<default_value>443</default_value>
		</field>
		<field>
			<fielddescr>reverse HTTPS default site</fielddescr>
			<fieldname>reverse_https_defsite</fieldname>
			<description>This is the HTTPS reverse default site. (leave empty to use the external fqdn)</description>
			<type>input</type>
			<size>60</size>
			<default_value>localhost</default_value>
		</field>

		<field>
			<fielddescr>reverse SSL Certificate</fielddescr>
			<fieldname>reverse_ssl_cert</fieldname>
			<description>Choose the SSL Server Certificate here.</description>
			<type>select_source</type>
			<source><![CDATA[squid_get_server_certs()]]></source>
			<source_name>descr</source_name>
			<source_value>refid</source_value>
		</field>
		
		<field>
			<fielddescr>Ignore internal Certificate validation.</fielddescr>
			<fieldname>ignore_ssl_valid</fieldname>
			<description>If this field is checked, internal certificate validation will be ignored.</description>
			<type>checkbox</type>
			<required/>
			<default_value>on</default_value>
		</field>
		<field>
			<fielddescr>extension methods</fielddescr>
			<fieldname>extension_methods</fieldname>
			<description>This field defines additional extension methods for the proxy to use. (RPC_IN_DATA RPC_OUT_DATA for RPC over HTTP -> Outlook Anywhere)</description>
			<type>input</type>
			<size>80</size>
			<default_value>RPC_IN_DATA RPC_OUT_DATA</default_value>
		</field>
		<field>
			<fielddescr>Reset TCP connections if request is unauthorized.</fielddescr>
			<fieldname>deny_info_tcp_reset</fieldname>
			<description>If this field is checked, the reverse-proxy will reset the TCP connection if the request is unauthorized.</description>
			<type>checkbox</type>
			<default_value>on</default_value>
		</field>
    		
		<field>
			<fielddescr>published server peer IP</fielddescr>
			<fieldname>reverse_cache_peer</fieldname>
			<description>This is the internal published server peer IP.</description>
			<type>input</type>
			<size>15</size>
			<default_value>internalhost</default_value>
		</field>

		<field>
			<fielddescr>published server peer port</fielddescr>
			<fieldname>reverse_cache_peer_port</fieldname>
			<description>This is the internal published server peer port.</description>
			<type>input</type>
			<size>5</size>
			<default_value>80</default_value>
		</field>
    
		<field>
			<fielddescr>published URL</fielddescr>
			<fieldname>reverse_acl</fieldname>
			<description>This is the URL to publish.</description>
			<type>input</type>
			<size>60</size>
		</field>

	</fields>
	<custom_php_command_before_form>
		squid_before_form_general(&amp;$pkg);
	</custom_php_command_before_form>
	<custom_php_validation_command>
		squid_validate_reverse($_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_php_resync_config_command>
		squid_resync();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/config/snort-dev/snort_whitelist.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 to whom it may belong
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>snortglobal</name>
	<version>0.1.0</version>
	<title>Snort: Whitelist</title>
	<include_file>/usr/local/pkg/snort/snort.inc</include_file>
	<!-- Menu is where this packages menu will appear -->
	<tabs>
		<tab>
			<text>Snort Inertfaces</text>
			<url>/snort/snort_interfaces.php</url>
		</tab>
		<tab>
			<text>Global Settings</text>
			<url>/snort/snort_interfaces_global.php</url>
		</tab>
		<tab>
			<text>Rule Updates</text>
			<url>/snort/snort_download_rules.php</url>
		</tab>
		<tab>
			<text>Alerts</text>
			<url>/snort/snort_alerts.php</url>
		</tab>
		<tab>
			<text>Blocked</text>
			<url>/snort/snort_blocked.php</url>
		</tab>
		<tab>
			<text>Whitelist</text>
			<url>/pkg.php?xml=/snort_whitelist.xml</url>
			<active/>
		</tab>
		<tab>
			<text>Help Info</text>
			<url>/snort/snort_help_info.php</url>
		</tab>
	</tabs>
	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Whitelisted IP</fielddescr>
			<fieldname>ip</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
		</columnitem>
	</adddeleteeditpagefields>
	<fields>
		<field>
			<fielddescr>Whitelisted IP</fielddescr>
			<fieldname>ip</fieldname>
			<description>Enter the IP or network to whitelist from snort blocking.  Network items should be expressed in CIDR notation.  Example: 0.0.0.0/24 or 0.0.0.0/32</description>
			<type>input</type>
			<size>40</size>
		</field>
		<field>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
			<description>Enter the description for this item</description>
			<type>input</type>
			<size>60</size>
		</field>
	</fields>
	<custom_php_command_before_form>
	</custom_php_command_before_form>
	<custom_delete_php_command>
	</custom_delete_php_command>
	<custom_php_resync_config_command>
		create_snort_conf();
	</custom_php_resync_config_command>
</packagegui>
