=== 007au/pfsense-packages/config/schema/packages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ...................................................................... -->
<!-- pfSense Package DTD V1.0 ............................................. -->
<!-- File package.dtd ..................................................... -->
<!--
/* $Id$ */
/* ========================================================================== */
/*
    package.dtd
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
-->
<!--
  |
  | May be parsed using http://dtdparse.sourceforge.net/ to generate an
  | HTML document that describes this DTD.
  |
-->
<!-- Indicates the version of a package -->
<!ELEMENT version (#PCDATA)>
<!-- Indicates where to get more informations about this package -->
<!ELEMENT url (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT depends_on_service (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT tooltiptext (#PCDATA)>
<!-- The title of a particular package -->
<!ELEMENT title (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT textneeded (#PCDATA)>
<!-- Categroy of a particular package (e.g. System) -->
<!ELEMENT category (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT note (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT savetext (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT preoutput (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT donotsave (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT text (#PCDATA)>
<!-- Container element. Contains several tab elements -->
<!ELEMENT tabs ((tab*))>
<!-- A specific tab that is part of a tab pane -->
<!ELEMENT tab ((text, url, active?))>
<!-- A service that may be executed while starting the system -->
<!ELEMENT service ((name, rcfile?, executable?, description?))>
<!-- needs to be documented -->
<!ELEMENT section (#PCDATA)>
<!-- Indicates what particular kind of components may be required to run this package -->
<!ELEMENT requirements (#PCDATA)>
<!-- Shell script that is beeing used to start and stop a service -->
<!ELEMENT rcfile (#PCDATA)>
<!-- Executable that represents a service -->
<!ELEMENT executable (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT prefix (#PCDATA)>
<!-- Root node of a package definition. Container element -->
<!ELEMENT packagegui ((copyright, description, requirements, faq, name, version, title, category?, note?, savetext?, preoutput?, donotsave?, aftersaveredirect?, include_file?, backup_file?, delete_string?, addedit_string?, menu*, service*, modify_system?, tabs?, configpath?, adddeleteeditpagefields?, additional_files_needed*, fields?, custom_php_global_functions?, custom_php_command_before_form?, custom_delete_php_command?, custom_add_php_command?, custom_php_resync_config_command?, custom_php_validation_command?, custom_add_php_command_late?, start_command?, restart_command?, process_kill_command?, custom_php_after_form_command?, custom_php_resync_config_command?, custom_php_install_command?, custom_php_deinstall_command?, custom_php_before_form_command?, custom_php_after_head_command?, templates?))>
<!-- A particular name -->
<!ELEMENT name (#PCDATA)>
<!-- Menu item. Container element -->
<!ELEMENT menu ((name, tooltiptext?, section?, configfile?, url?, depends_on_service?))>
<!-- needs to be documented -->
<!ELEMENT modifyitem ((modifyfilename?, textneeded?))>
<!-- needs to be documented -->
<!ELEMENT item (#PCDATA)>
<!-- A PHP file that needs to be included prior to executing arbitrary PHP code -->
<!ELEMENT include_file (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT backup_file (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT delete_string (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT addedit_string (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT aftersaveredirect (#PCDATA)>
<!-- FAQ items or an URL that points to certain FAQ items -->
<!ELEMENT faq (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT modifyfilename (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT modify_system ((modifyitem+))>
<!-- needs to be documented -->
<!ELEMENT rowhelperfield ((fielddescr, fieldname, description, type, size?, options?))>
<!-- needs to be documented -->
<!ELEMENT rowhelper ((rowhelperfield+))>
<!-- needs to be documented -->
<!ELEMENT size (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT donotdisable (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT enablefields (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT required EMPTY>
<!-- needs to be documented -->
<!ELEMENT multiple (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT default_value (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT value (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT type (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT cols (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT rows (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT combinefieldsbegin (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT combinefieldsend (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT dontdisplayname (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT dontcombinecells (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT onchange (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT encoding (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT typehint (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT options ((option+))>
<!-- needs to be documented -->
<!ELEMENT option ((name, value))>
<!-- needs to be documented -->
<!ELEMENT fields ((field*))>
<!-- needs to be documented -->
<!ELEMENT filename (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT fieldname (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT fielddescr (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT validationtype (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT field ((fielddescr, fieldname, description?, type, donotdisable?, enablefields?, size?, required?, default_value?, value?, multiple?, options?, cols?, rows?, typehint?, onchange?, encoding?, combinefieldsend?, combinefieldsbegin?, rowhelper?, dontdisplayname?, dontcombinecells?, validationtype?))>
<!-- needs to be documented -->
<!ELEMENT description (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_global_functions (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_command_before_form (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_delete_php_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_add_php_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_resync_config_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_validation_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_add_php_command_late (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT process_kill_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT start_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT restart_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_after_form_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_install_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_deinstall_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_after_head_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_before_form_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT copyright (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT configpath (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT configfile (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT chmod (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT columnitem ((fielddescr, fieldname))>
<!-- needs to be documented -->
<!ELEMENT adddeleteeditpagefields ((columnitem+))>
<!-- needs to be documented -->
<!ELEMENT additional_files_needed ((prefix?, chmod?, item))>
<!-- needs to be documented -->
<!ELEMENT active EMPTY>
<!-- needs to be documented -->
<!ELEMENT templates ((template+))>
<!-- needs to be documented -->
<!ELEMENT templatecontents (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT template ((filename, templatecontents))>
<!-- End of pfSense package DTD V1.0 ...................................... -->
<!-- ...................................................................... -->

=== 007au/pfsense-packages/config/sarg/sarg_schedule.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* ========================================================================== */
/*
    sarg_schedule.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2012 Marcello Coutinho
    All rights reserved.                                                      
*/
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>sargschedule</name>
	<version>0.5</version>
	<title>Status: Sarg Schedules</title>
	<include_file>/usr/local/pkg/sarg.inc</include_file>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
		<item>http://www.pfsense.com/packages/config/sarg/sarg.inc</item>
	</additional_files_needed>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
		<item>http://www.pfsense.com/packages/config/sarg/sarg_sync.xml</item>
	</additional_files_needed>
	<menu>
		<name>sarg</name>
		<tooltiptext>sarg</tooltiptext>
		<section>Diagnostics</section>
		<configfile>sarg.xml</configfile>
	</menu>
	<tabs>
		<tab>
			<text>General</text>
			<url>/pkg_edit.php?xml=sarg.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Users</text>
			<url>/pkg_edit.php?xml=sarg_users.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Schedule</text>
			<url>/pkg.php?xml=sarg_schedule.xml&amp;id=0</url>
			<active/>
		</tab>
		<tab>
			<text>View Report</text>
			<url>/sarg_reports.php</url>
		</tab>
		<tab>
			<text>Realtime</text>
			<url>/sarg_realtime.php</url>
		</tab>
		<tab>
			<text>XMLRPC Sync</text>
			<url>/pkg_edit.php?xml=sarg_sync.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Help</text>
			<url>/sarg_about.php</url>
		</tab>
	</tabs>
	<adddeleteeditpagefields>
		<columnitem>
			<fielddescr>Status</fielddescr>
			<fieldname>enable</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Update Frequency</fielddescr>
			<fieldname>frequency</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Aditional Args</fielddescr>
			<fieldname>mod</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Post Action</fielddescr>
			<fieldname>action</fieldname>
		</columnitem>
		<columnitem>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
		</columnitem>	
	</adddeleteeditpagefields>
	<fields>
		<field>
			<type>listtopic</type>
			<fieldname>temp</fieldname>
			<name>Schedule Options</name>
		</field>
		<field>
			<fielddescr>Enable</fielddescr>
			<fieldname>enable</fieldname>
			<type>checkbox</type>
			<description>Enable this schedule</description>
		</field>	
		<field>
			<fielddescr>Description</fielddescr>
			<fieldname>description</fieldname>
			<description>Enter a description for this file.</description>
			<type>input</type>
			<size>60</size>
		</field>
		<field>
			<fielddescr>Sarg args</fielddescr>
			<fieldname>args</fieldname>
			<description>Enter sarg extra args to run on this schedule.</description>
			<type>input</type>
			<size>25</size>
		</field>
		<field>
			<fielddescr>frequency</fielddescr>
			<fieldname>frequency</fieldname>
			<type>input</type>
			<size>10</size>
			<description><![CDATA[How often extract users from active directory and verify changes<br>
							Valid options are minutes(m), hours(h), days(d)<br>
							Sample: To update every hour, use 1h<br><br>]]>&lt;input type=&quot;submit&quot; name=&quot;Submit&quot; value=&quot;Force udpate now&quot;&gt;&lt;br&gt;</description>
			<required/>
		</field>
		<field>
			<fielddescr>Action after sarg</fielddescr>
			<fieldname>action</fieldname>
			<type>select</type>
 				<options>
 				<option><name>None(default)</name><value>none</value></option>
				<option><name>rotate logs</name><value>rotate</value></option>
				<option><name>Restart proxy daemon</name><value>restart</value></option>
				<option><name>Rotate log and restart proxy daemon</name><value>both</value></option>
				</options>
			<description>Choose an action after sarg finishes</description>
		</field>
	</fields>
	<custom_php_install_command>
		sarg_php_install_command();
	</custom_php_install_command>
	<custom_php_command_before_form>
	</custom_php_command_before_form>
	<custom_php_validation_command>
		sarg_validate_input($_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_delete_php_command>
		sync_package_sarg();
	</custom_delete_php_command>	
	<custom_php_resync_config_command>
		sarg_resync();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/config/postfix/postfix_recipients.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
	<copyright>
	<![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    postfix_recipients.xml
    part of the Postfix package for pfSense
    Copyright (C) 2011 Marcello Coutinho
    All rights reserved.            
*/
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
	]]>
	</copyright>
	<description>Describe your package here</description>
	<requirements>Describe your package requirements here</requirements>
	<faq>Currently there are no FAQ items provided.</faq>
	<name>postfixrecipients</name>
	<version>1.0</version>
	<title>Services: Postfix relay and antispam</title>
	<include_file>/usr/local/pkg/postfix.inc</include_file>
	<menu>
		<name>Postfix Antispam and mail Relay</name>
		<tooltiptext>Configure Postfix Forwarder</tooltiptext>
		<section>Services</section>
		<url>pkg_edit.php?xml=postfix.xml&amp;id=0</url>
	</menu>
	<service>
		<name>postfix</name>
		<rcfile>postfix.sh</rcfile>
		<executable>master</executable>
	</service>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix.inc</item>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix_acl.xml</item>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix_recipients.xml</item>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix_antispam.xml</item>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>

		<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix_sync.xml</item>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>
		<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix_view_config.php</item>
		<prefix>/usr/local/www/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix_recipients.php</item>
		<prefix>/usr/local/www/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>
<tabs>
		<tab>
			<text>General</text>
			<url>/pkg_edit.php?xml=postfix.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>ACLs / Filter Maps</text>
			<url>/pkg_edit.php?xml=postfix_acl.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>Valid recipients</text>
			<url>/pkg_edit.php?xml=postfix_recipients.xml&amp;id=0</url>
			<active/>
		</tab>
		<tab>
			<text>Antispam</text>
			<url>/pkg_edit.php?xml=postfix_antispam.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>XMLRPC Sync</text>
			<url>/pkg_edit.php?xml=postfix_sync.xml&amp;id=0</url>
		</tab>
		<tab>
			<text>View config files</text>
			<url>/postfix_view_config.php</url>
		</tab>
				<tab>
			<text>Search Email</text>
			<url>/postfix_search.php</url>
		</tab>
</tabs>
	<fields>
		<field>
			<name>Get Valid recipients from Active Directory</name>
			<type>listtopic</type>
		</field>
		<field>
			<fielddescr>Enable LDAP fetch</fielddescr>
			<fieldname>enable_ldap</fieldname>
			<type>checkbox</type>
			<description><![CDATA[Extract valid email addresses from Active Directory.<br>
								Before using LDAP fetch you must install p5-perl-ldap package(hint: <strong>/usr/sbin/pkg_add -r p5-perl-ldap</strong>)]]></description>
		</field>
		<field>
			<fielddescr>Frequency</fielddescr>
			<fieldname>freq</fieldname>
			<description>Wait time between each fetch HINT 30m(30 minutes), 1h(one hour), 1d(one day)</description>
			<type>input</type>
			<size>15</size>
		</field>
		<field>
			<fielddescr><![CDATA[<strong>HINTS</strong><br>Hostname:<br>dc1.mysite.com<br><br>Domain:<br>dc=mysite,dc=com<br><br>Username:<br>cn=antispam,cn=Users<br>]]></fielddescr>
			<fieldname>none</fieldname>
			<type>rowhelper</type>
			<rowhelper>
			<rowhelperfield>
				<fielddescr>Hostname</fielddescr>
				<fieldname>dc</fieldname>
				<type>input</type>
				<size>20</size>
			</rowhelperfield>
			<rowhelperfield>
				<fielddescr>Domain</fielddescr>
				<fieldname>cn</fieldname>
				<type>input</type>
				<size>22</size>
			</rowhelperfield>
			<rowhelperfield>
				<fielddescr>Username</fielddescr>
				<fieldname>username</fieldname>
				<type>input</type>
				<size>20</size>
			</rowhelperfield>
			<rowhelperfield>
				<fielddescr>Password</fielddescr>
				<fieldname>password</fieldname>
				<type>password</type>
				<size>10</size>
			</rowhelperfield>
			</rowhelper>
		</field>
		<field>
			<name>Get Valid recipients from local file</name>
			<type>listtopic</type>
		</field>
		<field>
			<fielddescr>Location</fielddescr>
			<name>location</name>
			<type>input</type>
			<size>80</size>
		</field>
		<field>
			<name>Custom Valid recipients</name>
			<type>listtopic</type>
		</field>
		<field>
			<fielddescr>Custom list</fielddescr>
			<fieldname>custom_recipients</fieldname>
			<description><![CDATA[Paste your valid recipients here, one per line. <strong>HINT user@mycompany.com OK</strong>]]></description>
			<type>textarea</type>
			<cols>60</cols>
			<rows>15</rows>
			<encoding>base64</encoding>
		</field>
	</fields>
	<custom_php_install_command>
		postfix_php_install_command();
	</custom_php_install_command>
	<custom_php_deinstall_command>
		postfix_php_deinstall_command();
	</custom_php_deinstall_command>
	<custom_php_validation_command>
		postfix_validate_input($_POST, &amp;$input_errors);
	</custom_php_validation_command>	
	<custom_php_resync_config_command>
		sync_package_postfix();
	</custom_php_resync_config_command>
</packagegui>

=== 007au/pfsense-packages/config/postfix/postfix.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
	<copyright>
	<![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    postfix.xml
    part of the Postfix package for pfSense
    Copyright (C) 2010 Erik Fonnesbeck
    All rights reserved.            
                                                                  */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
	]]>
	</copyright>
	<description>Describe your package here</description>
	<requirements>Describe your package requirements here</requirements>
	<faq>Currently there are no FAQ items provided.</faq>
	<name>postfix</name>
	<version>1.1</version>
	<title>Services: Postfix Forwarder</title>
	<include_file>/usr/local/pkg/postfix.inc</include_file>
	<menu>
		<name>Postfix Forwarder</name>
		<tooltiptext>Configure Postfix Forwarder</tooltiptext>
		<section>Services</section>
		<url>pkg_edit.php?xml=postfix.xml&amp;id=0</url>
	</menu>
	<service>
		<name>postfix</name>
		<rcfile>postfix.sh</rcfile>
		<executable>master</executable>
	</service>
	<additional_files_needed>
		<item>http://www.pfsense.org/packages/config/postfix/postfix.inc</item>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
	</additional_files_needed>
	<fields>
		<field>
			<name>Posftix General Settings</name>
			<type>listtopic</type>
		</field>
		<field>
			<fielddescr>Maximum message size</fielddescr>
			<fieldname>message_size_limit</fieldname>
			<type>input</type>
			<description>
				This setting governs the largest message size that will be accepted by this mail server. Ensure you have enough space to accommodate this size, and ensure this setting matches or is lower than the destination server(s).&lt;br/&gt;Default: 10240000 (10MB).
			</description>
		</field>
		<field>
			<name>Domains to Forward</name>
			<type>listtopic</type>
		</field>
		<field>
			<fielddescr>Forwarding</fielddescr>
			<fieldname>none</fieldname>
			<type>rowhelper</type>
			<rowhelper>
			<rowhelperfield>
				<fielddescr>Domain</fielddescr>
				<fieldname>domain</fieldname>
				<description>Enter the domain here (ex: example.com)</description>
				<type>input</type>
				<size>20</size>
			</rowhelperfield>
			<rowhelperfield>
				<fielddescr>Mail Server IP</fielddescr>
				<fieldname>mailserverip</fieldname>
				<description>Enter the mail server IP to forward to here.</description>
				<type>input</type>
				<size>20</size>
			</rowhelperfield>
			</rowhelper>
		</field>
	</fields>
	<custom_php_install_command>
		postfix_php_install_command();
	</custom_php_install_command>
	<custom_php_deinstall_command>
		postfix_php_deinstall_command();
	</custom_php_deinstall_command>
	<custom_php_validation_command>
		postfix_validate_input($_POST, &amp;$input_errors);
	</custom_php_validation_command>	
	<custom_php_resync_config_command>
		sync_package_postfix();
	</custom_php_resync_config_command>
</packagegui>
