=== 007au/pfsense-packages/config/schema/packages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ...................................................................... -->
<!-- pfSense Package DTD V1.0 ............................................. -->
<!-- File package.dtd ..................................................... -->
<!--
/* $Id$ */
/* ========================================================================== */
/*
    package.dtd
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
-->
<!--
  |
  | May be parsed using http://dtdparse.sourceforge.net/ to generate an
  | HTML document that describes this DTD.
  |
-->
<!-- Indicates the version of a package -->
<!ELEMENT version (#PCDATA)>
<!-- Indicates where to get more informations about this package -->
<!ELEMENT url (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT depends_on_service (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT tooltiptext (#PCDATA)>
<!-- The title of a particular package -->
<!ELEMENT title (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT textneeded (#PCDATA)>
<!-- Categroy of a particular package (e.g. System) -->
<!ELEMENT category (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT note (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT savetext (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT preoutput (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT donotsave (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT text (#PCDATA)>
<!-- Container element. Contains several tab elements -->
<!ELEMENT tabs ((tab*))>
<!-- A specific tab that is part of a tab pane -->
<!ELEMENT tab ((text, url, active?))>
<!-- A service that may be executed while starting the system -->
<!ELEMENT service ((name, rcfile?, executable?, description?))>
<!-- needs to be documented -->
<!ELEMENT section (#PCDATA)>
<!-- Indicates what particular kind of components may be required to run this package -->
<!ELEMENT requirements (#PCDATA)>
<!-- Shell script that is beeing used to start and stop a service -->
<!ELEMENT rcfile (#PCDATA)>
<!-- Executable that represents a service -->
<!ELEMENT executable (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT prefix (#PCDATA)>
<!-- Root node of a package definition. Container element -->
<!ELEMENT packagegui ((copyright, description, requirements, faq, name, version, title, category?, note?, savetext?, preoutput?, donotsave?, aftersaveredirect?, include_file?, backup_file?, delete_string?, addedit_string?, menu*, service*, modify_system?, tabs?, configpath?, adddeleteeditpagefields?, additional_files_needed*, fields?, custom_php_global_functions?, custom_php_command_before_form?, custom_delete_php_command?, custom_add_php_command?, custom_php_resync_config_command?, custom_php_validation_command?, custom_add_php_command_late?, start_command?, restart_command?, process_kill_command?, custom_php_after_form_command?, custom_php_resync_config_command?, custom_php_install_command?, custom_php_deinstall_command?, custom_php_before_form_command?, custom_php_after_head_command?, templates?))>
<!-- A particular name -->
<!ELEMENT name (#PCDATA)>
<!-- Menu item. Container element -->
<!ELEMENT menu ((name, tooltiptext?, section?, configfile?, url?, depends_on_service?))>
<!-- needs to be documented -->
<!ELEMENT modifyitem ((modifyfilename?, textneeded?))>
<!-- needs to be documented -->
<!ELEMENT item (#PCDATA)>
<!-- A PHP file that needs to be included prior to executing arbitrary PHP code -->
<!ELEMENT include_file (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT backup_file (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT delete_string (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT addedit_string (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT aftersaveredirect (#PCDATA)>
<!-- FAQ items or an URL that points to certain FAQ items -->
<!ELEMENT faq (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT modifyfilename (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT modify_system ((modifyitem+))>
<!-- needs to be documented -->
<!ELEMENT rowhelperfield ((fielddescr, fieldname, description, type, size?, options?))>
<!-- needs to be documented -->
<!ELEMENT rowhelper ((rowhelperfield+))>
<!-- needs to be documented -->
<!ELEMENT size (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT donotdisable (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT enablefields (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT required EMPTY>
<!-- needs to be documented -->
<!ELEMENT multiple (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT default_value (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT value (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT type (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT cols (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT rows (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT combinefieldsbegin (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT combinefieldsend (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT dontdisplayname (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT dontcombinecells (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT onchange (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT encoding (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT typehint (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT options ((option+))>
<!-- needs to be documented -->
<!ELEMENT option ((name, value))>
<!-- needs to be documented -->
<!ELEMENT fields ((field*))>
<!-- needs to be documented -->
<!ELEMENT filename (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT fieldname (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT fielddescr (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT validationtype (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT field ((fielddescr, fieldname, description?, type, donotdisable?, enablefields?, size?, required?, default_value?, value?, multiple?, options?, cols?, rows?, typehint?, onchange?, encoding?, combinefieldsend?, combinefieldsbegin?, rowhelper?, dontdisplayname?, dontcombinecells?, validationtype?))>
<!-- needs to be documented -->
<!ELEMENT description (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_global_functions (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_command_before_form (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_delete_php_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_add_php_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_resync_config_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_validation_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_add_php_command_late (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT process_kill_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT start_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT restart_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_after_form_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_install_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_deinstall_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_after_head_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT custom_php_before_form_command (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT copyright (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT configpath (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT configfile (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT chmod (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT columnitem ((fielddescr, fieldname))>
<!-- needs to be documented -->
<!ELEMENT adddeleteeditpagefields ((columnitem+))>
<!-- needs to be documented -->
<!ELEMENT additional_files_needed ((prefix?, chmod?, item))>
<!-- needs to be documented -->
<!ELEMENT active EMPTY>
<!-- needs to be documented -->
<!ELEMENT templates ((template+))>
<!-- needs to be documented -->
<!ELEMENT templatecontents (#PCDATA)>
<!-- needs to be documented -->
<!ELEMENT template ((filename, templatecontents))>
<!-- End of pfSense package DTD V1.0 ...................................... -->
<!-- ...................................................................... -->

=== 007au/pfsense-packages/config/imspector/imspector.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Ryan Wagoner <rswagoner@gmail.com>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>imspector</name>
	<version>0.5</version>
	<title>Services: IMSpector</title>
	<savetext>Change</savetext>
	<aftersaveredirect>/services_imspector_logs.php</aftersaveredirect>
	<include_file>/usr/local/pkg/imspector.inc</include_file>
	<menu>
		<name>IMSpector</name>
		<tooltiptext>Set IMSpector settings such as protocols to listen on.</tooltiptext>
		<section>Services</section>
		<url>/services_imspector_logs.php</url>
	</menu>
	<service>
		<name>imspector</name>
		<rcfile>imspector.sh</rcfile>
		<executable>imspector</executable>
	</service>
	<tabs>
		<tab>
			<text>IMSpector Log Viewer</text>
			<url>/services_imspector_logs.php</url>
		</tab>
		<tab>
			<text>IMSpector Settings</text>
			<url>/pkg_edit.php?xml=imspector.xml&amp;id=0</url>
			<active/>
		</tab>
	</tabs>
	<additional_files_needed>
	    <prefix>/usr/local/pkg/</prefix>
		<chmod>0755</chmod>
		<item>http://www.pfsense.org/packages/config/imspector/imspector.inc</item>
	</additional_files_needed>
	<additional_files_needed>
	    <prefix>/usr/local/www/</prefix>
		<chmod>0755</chmod>
		<item>http://www.pfsense.org/packages/config/imspector/services_imspector_logs.php</item>
	</additional_files_needed>
	<fields>
		<field>
			<fielddescr>Enable IMSpector</fielddescr>
			<fieldname>enable</fieldname>
			<type>checkbox</type>
		</field>			
		<field>
			<fielddescr>Interfaces (generally LAN)</fielddescr>
			<fieldname>iface_array</fieldname>
			<description>You can use the CTRL or COMMAND key to select multiple interfaces.</description>
			<type>interfaces_selection</type>
			<size>3</size>
			<required/>
			<value>lan</value>
			<multiple>true</multiple>
		</field>
		<field>
			<fielddescr>Listen on protocols</fielddescr>
			<fieldname>proto_array</fieldname>
			<description>You can use the CTRL or COMMAND key to select multiple protocols.</description>
			<type>select</type>
			<size>4</size>
			<required/>
			<multiple>true</multiple>
 			<options>
 				<option>
 					<name>MSN</name>
 					<value>msn</value>
 				</option>
 				<option>
					<name>ICQ/AIM</name>
 					<value>icq</value>
				</option>
 				<option>
					<name>Yahoo</name>
 					<value>yahoo</value>
				</option>
 				<option>
					<name>IRC</name>
 					<value>irc</value>
 				</option>			
			</options>
		</field>
		<field>
			<fielddescr>Enable file logging</fielddescr>
			<fieldname>log_file</fieldname>
			<description>Log files stored in /var/imspector.</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Enable mySQL logging</fielddescr>
			<fieldname>log_mysql</fieldname>
			<description>Make sure to specify your MySQL credentials below.</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>mySQL server</fielddescr>
			<fieldname>mysql_server</fieldname>
			<type>input</type>
		</field>
		<field>
			<fielddescr>mySQL database</fielddescr>
			<fieldname>mysql_database</fieldname>
			<type>input</type>
		</field>
		<field>
			<fielddescr>mySQL username</fielddescr>
			<fieldname>mysql_username</fieldname>
			<type>input</type>
		</field>
		<field>
			<fielddescr>mySQL password</fielddescr>
			<fieldname>mysql_password</fieldname>
			<type>password</type>
		</field>
		<field>
			<fielddescr>Enable bad word filtering</fielddescr>
			<fieldname>filter_badwords</fieldname>
			<description>Replace characters of matched bad word with *.</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Bad words list</fielddescr>
			<fieldname>badwords_list</fieldname>
			<description>
				Place one word or phrase to match per line.&lt;br /&gt;
				If left blank the default list in /usr/local/etc/imspector/badwords.txt will be used.
			</description>
			<type>textarea</type>
			<encoding>base64</encoding>
			<rows>5</rows>
			<cols>40</cols>
		</field>
		<field>
			<fielddescr>Block file transfers</fielddescr>
			<fieldname>block_files</fieldname>
			<description>Block file transfers on supported protocols.</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Block non ACL defined</fielddescr>
			<fieldname>block_unlisted</fieldname>
			<description>Overide the default of allowing user's not defined the whitelist or blacklist ACLs.</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>ACL whitelist</fielddescr>
			<fieldname>acl_whitelist</fieldname>
			<description>
				Example (allow specifc access): localuser: remoteuser1 remoteuser2&lt;br /&gt;
				Example (allow full access): localuser:
			</description>
			<type>textarea</type>
			<encoding>base64</encoding>
			<rows>5</rows>
			<cols>40</cols>
		</field>
		<field>
			<fielddescr>ACL blacklist</fielddescr>
			<fieldname>acl_blacklist</fieldname>
			<description>
				Example (block specifc access): localuser: remoteuser1 remoteuser2&lt;br /&gt;
				Example (block all access): localuser:
			</description>
			<type>textarea</type>
			<encoding>base64</encoding>
			<rows>5</rows>
			<cols>40</cols>
		</field>
	</fields>
	<custom_php_validation_command>
		validate_form_imspector($_POST, &amp;$input_errors);
	</custom_php_validation_command>
	<custom_php_resync_config_command>
		sync_package_imspector();
	</custom_php_resync_config_command>    
	<custom_php_deinstall_command>
		deinstall_package_imspector();
	</custom_php_deinstall_command>
</packagegui>

=== 007au/pfsense-packages/config/vnstat2/vnstat2.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
    <copyright></copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>vnstat2</name>
	<version>1.0</version>
	<title>vnstat2</title>
	<aftersaveredirect>/pkg_edit.php?xml=vnstat2.xml&amp;id=0</aftersaveredirect>
	<include_file>/usr/local/pkg/vnstat2.inc</include_file>
	<menu>
		<name>vnstat2</name>
		<tooltiptext></tooltiptext>
		<section>Status</section>
		<url>/vnstat2</url>
	</menu>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0644</chmod>
		<item>http://www.pfsense.com/packages/config/vnstat2/vnstat2.inc</item>
	</additional_files_needed>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0644</chmod>
		<item>http://www.pfsense.com/packages/config/vnstat2/bin/vnstat_php_frontend-1.4.1.tar.gz</item>
	</additional_files_needed>
	<additional_files_needed>
		<prefix>/usr/local/pkg/</prefix>
		<chmod>0644</chmod>
		<item>http://www.pfsense.com/packages/config/vnstat2/bin/vnstat.conf</item>
	</additional_files_needed>
	<custom_php_resync_config_command></custom_php_resync_config_command>
	<custom_php_install_command>vnstat_install_config();</custom_php_install_command>
	<custom_php_deinstall_command>vnstat_install_deinstall();</custom_php_deinstall_command>
</packagegui>

=== 007au/pfsense-packages/config/Fit123/ddns.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "../schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
    <copyright></copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>ddns</name>
	<title>DDNS</title>
	<include_file>/usr/local/pkg/fit123.inc</include_file>
	<tabs>
		<tab>
			<text>Fit123</text>
			<url>/pkg_edit.php?xml=fit123.xml&amp;id=0</url>
			<active/>
		</tab>
		<tab>
			<text>DDNS</text>
			<url>/pkg_edit.php?xml=ddns.xml&amp;id=0</url>
		</tab>
	</tabs>
	<fields>
		<field>
			<fielddescr>Dynamic DNS</fielddescr>
			<fieldname>enable</fieldname>
			<description>
			A more customize way to update dynamic dns and mainly for IP's that doesn't change very often.&lt;br&gt;
			Will check for ip change every 5 min via local shell script and will only contact provider on change.&lt;br&gt;
			(needs a reboot, hopefully it can be changed )
			</description>
			<type>checkbox</type>
		</field>
		<field>
			<fielddescr>Enter string that should be phrased</fielddescr>
			<fieldname>line1</fieldname>
			<description>
			String for OpenDNS should look like:&lt;br&gt;
			https://username:password@updates.opendns.com/nic/update?hostname=
			</description>
			<type>textarea</type>
			<cols>80</cols>
                        <rows>1</rows>
		</field>
		<field>
			<fielddescr>Enter 2th string that should be phrased</fielddescr>
			<fieldname>line2</fieldname>
			<description>Leave empty if not used</description>
			<type>textarea</type>
			<cols>80</cols>
                        <rows>1</rows>
		</field>
		<field>
			<fielddescr>Enter 3th string that should be phrased</fielddescr>
			<fieldname>line3</fieldname>
			<description>Leave empty if not used</description>
			<type>textarea</type>
			<cols>80</cols>
                        <rows>1</rows>
		</field>
	</fields>
	<custom_add_php_command></custom_add_php_command>
        <custom_php_command_before_form>ddns_config();</custom_php_command_before_form>
	<custom_php_after_form_command></custom_php_after_form_command>
	<custom_php_validation_command></custom_php_validation_command>
	<custom_php_resync_config_command></custom_php_resync_config_command>
	<custom_php_install_command>Fit123_install_config();</custom_php_install_command>
	<custom_php_deinstall_command>Fit123_install_deinstall();</custom_php_deinstall_command>
</packagegui>

=== 007au/pfsense-packages/config/archive/upclient.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE packagegui SYSTEM "./schema/packages.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/package.xsl"?>
<packagegui>
        <copyright>
        <![CDATA[
/* $Id$ */
/* ========================================================================== */
/*
    authng.xml
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 to whom it may belong
    All rights reserved.

    Based on m0n0wall (http://m0n0.ch/wall)
    Copyright (C) 2003-2006 Manuel Kasper <mk@neon1.net>.
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */
        ]]>
        </copyright>
    <description>Describe your package here</description>
    <requirements>Describe your package requirements here</requirements>
    <faq>Currently there are no FAQ items provided.</faq>
	<name>upclient</name>
	<version>5.0.b8_2</version>
	<title>upclient: Settings</title>
	<aftersaveredirect>pkg_edit.php?xml=upclient.xml&amp;id=0</aftersaveredirect>
	<menu>
                <name>upclient</name>
                <tooltiptext>Modify upclient settings.</tooltiptext>
                <section>Services</section>
                <configfile>upclient.xml</configfile>
                <url>/pkg_edit.php?xml=upclient.xml&amp;id=0</url>
        </menu>
	<service>
                <name>upclient</name>
                <rcfile>upclient.sh</rcfile>
                <executable>upclient</executable>
        </service>
	<configpath>installedpackages->package->$packagename->configuration->settings</configpath>
	<fields>
		<field>
			<fielddescr>Authorization Key</fielddescr>
			<fieldname>authkey</fieldname>
			<description>This system's uptime authorization key.</description>
			<type>input</type>
		</field>
		<field>
			<fielddescr>Update Interval</fielddescr>
			<fieldname>interval</fieldname>
			<description>The interval between updates, in seconds (default 550).</description>
			<type>input</type>
		</field>
		<field>
			<fielddescr>Uptime Server</fielddescr>
			<fieldname>server</fieldname>
			<description>The server this system should send uptime reports to.</description>
			<type>input</type>
		</field>
	</fields>
	<custom_php_global_functions>
	function sync_package_upclient() {
		global $config;
                conf_mount_rw();
                config_lock();
		$upclient_conf = $config['installedpackages']['upclient']['config'][0];
		$fout = fopen("/usr/local/etc/upclient.conf", "w");
		if($upclient_conf['authkey'] and $upclient_conf['server']) {
			fwrite($fout, "PidFile = /var/run/upclient.pid # Location of pid file\n");
			fwrite($fout, "AuthKey = {$upclient_conf['authkey']}\n");
			$interval = $upclient_conf['interval'] ? $upclient_conf['interval'] : "550";
			fwrite($fout, "Interval = {$interval}\n");
			fwrite($fout, "UptimeServer = {$upclient_conf['server']}\n");
			$static = &lt;&lt;&lt;EOD
SendIdle      = 1       # Send CPU idle percent
SendUsage     = 1       # Send CPU load percent
SendOSName    = 1       # Send name of your Operating System
SendOSVersion = 1       # Send version of your OS
SendCPU       = 1       # Send CPU name of your machine
SendCPUDetail = 1       # (BSD, Linux &amp; Solaris only)
SendLoadAvg   = 1       # Send 15-minute Load-average (unix only)

EOD;
			fwrite($fout, $static);
			fclose($fout);
		}
		$start = "/usr/local/sbin/upclient &amp;";
		write_rcfile(array(
			"file" => "upclient.sh",
			"start" => $start
			)
		);
		restart_service("upclient");
                conf_mount_ro();
                config_unlock();
        }
	</custom_php_global_functions>
	<custom_add_php_command>
		sync_package_upclient();
	</custom_add_php_command>
</packagegui>
